# Generated by Django 4.2.2 on 2023-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceindexpage_listing_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceindexpage',
            name='listing_heading',
            field=models.CharField(default='Explore our Services', max_length=255, verbose_name='Services listing Heading'),
        ),
    ]
