# Generated by Django 4.1.9 on 2023-07-12 10:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtailiconchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicepage_what_we_do_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='what_we_do_items',
            field=wagtail.fields.StreamField([('what_we_do', wagtail.blocks.StructBlock([('icon', wagtailiconchooser.blocks.IconChooserBlock(label='Icon', required=False)), ('title', wagtail.blocks.CharBlock(max_length=60, required=False)), ('description', wagtail.blocks.CharBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
