# Generated by Django 4.2.7 on 2024-06-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicepage_introduction_button_link_external'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepage',
            options={'ordering': ['service__order'], 'verbose_name': 'Service Page', 'verbose_name_plural': 'Service Pages'},
        ),
    ]
