# Generated by Django 4.2.18 on 2025-03-03 10:00

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_servicepage_introduction_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='extra_content',
            field=wagtail.fields.StreamField([('title_text', 2), ('title_text_image', 4), ('accordion', 10), ('table', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section Title', 'max_length': 100, 'verbose_name': 'Section Title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'code', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'hr', 'anchor', 'table', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull', 'indent', 'outdent', 'html'], 'help_text': 'Section description', 'verbose_name': 'Section Text'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('image', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4']}), 8: ('wagtail.blocks.StructBlock', [[('heading', 6), ('description', 7), ('image', 3)]], {}), 9: ('wagtail.blocks.StreamBlock', [[('collapsibles', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('title', 5), ('collapsibles', 9)]], {}), 11: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': False, 'rowHeaders': False}}), 12: ('wagtail.blocks.StructBlock', [[('title', 5), ('table', 11)]], {})}, null=True),
        ),
    ]
