# Generated by Django 4.1.9 on 2023-05-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomBatchRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task ID')),
                ('task_complete', models.BooleanField(default=False, verbose_name='Task Complete')),
                ('event_registration_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.eventregistrationpage', verbose_name='Event Registration Page')),
            ],
        ),
    ]
