# Generated by Django 4.1.7 on 2023-05-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventregistrationpage_enable_mailing_list_subscription_and_more'),
        ('wagtailzoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoombatchregistration',
            name='event_registration_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.eventregistrationpage', verbose_name='Event Registration Page'),
        ),
        migrations.AlterField(
            model_name='zoombatchregistration',
            name='task_complete',
            field=models.BooleanField(default=False, verbose_name='Task Complete'),
        ),
        migrations.AlterField(
            model_name='zoombatchregistration',
            name='task_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Task ID'),
        ),
    ]
