# Generated by Django 4.2.2 on 2023-06-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationindexpage',
            options={'verbose_name': 'Organisation Index Page'},
        ),
        migrations.AddField(
            model_name='organisationindexpage',
            name='listing_heading',
            field=models.CharField(default='Explore our Organisation', max_length=255, verbose_name='Organisation listing Heading'),
        ),
    ]
