# Generated by Django 4.1.7 on 2023-05-02 11:22

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='location',
            field=models.CharField(help_text='Location of organisation', max_length=250, null=True, verbose_name='Location of organisation'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Thank you message'),
        ),
    ]
