# Generated by Django 4.1.7 on 2023-05-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactpage_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page'},
        ),
    ]
