# Generated by Django 4.0.10 on 2023-02-28 08:55

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactpage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_form_fields', to='contact.contactpage'),
        ),
    ]
