# Generated by Django 4.1.7 on 2023-03-04 22:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_formfield_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={},
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_details',
            field=wagtail.fields.StreamField([('contact_detail', wagtail.blocks.StructBlock([('fa_icon', wagtail.blocks.CharBlock(help_text="Font Awesome icon without the leading fas or fab. E.g for Envelope icon, fa-envelope. Check the correct icon at <a target='_blank' href='https://fontawesome.com/icons?c=communication&m=free'>Font Awesome</a>. Type in on the search bar on that page to filter.", max_length=20, required=False)), ('contact_type', wagtail.blocks.CharBlock(max_length=255)), ('contact_detail', wagtail.blocks.RichTextBlock(features=['bold', 'ul', 'ol', 'link', 'superscript', 'subscript']))]))], null=True, use_json_field=True),
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.AddField(
            model_name='contactformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_us_form_fields', to='contact.contactpage'),
        ),
    ]
