# Generated by Django 4.1.7 on 2023-03-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactformfield_alter_contactpage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='contact_details',
        ),
    ]
