# Generated by Django 4.1.9 on 2023-07-06 11:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='introduction_button_link',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='introduction_button_text',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='introduction_image',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='introduction_text',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='introduction_title',
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('feature_item', wagtail.blocks.StructBlock([('figure_type', wagtail.blocks.ChoiceBlock(choices=[('image', 'Image'), ('chart', 'Chart'), ('video', 'Video'), ('imageofchange', 'Image of Change')])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('chart_config_url', wagtail.blocks.URLBlock(help_text='A URL that returns Highcharts.js configuration, including the data', required=False)), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock(label='Description')), ('action_link_text', wagtail.blocks.CharBlock(max_length=15, required=False)), ('action_link', wagtail.blocks.PageChooserBlock(label='Action Link Internal', required=False)), ('action_link_external', wagtail.blocks.URLBlock(help_text='An external link to a detailed resource on the internet.If provided, the internal link will be ignored', max_length=400, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
