# Generated by Django 4.2.2 on 2023-08-04 07:50

from django.db import migrations
import pages.satellite_imagery.utils
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_imagery', '0002_satanimation_remove_satelliteimagerypage_msg_layers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satelliteimagerysetting',
            name='msg_layers',
            field=wagtail.fields.StreamField([('msg_layer', wagtail.blocks.StructBlock([('name', wagtail.blocks.ChoiceBlock(choices=pages.satellite_imagery.utils.get_msg_layer_choices, label='Layer name')), ('label', wagtail.blocks.CharBlock(help_text='Leave blank to use default label title from EUMetView', label='Layer label', max_length=255, required=False)), ('enabled', wagtail.blocks.BooleanBlock(default=True, label='Enabled', required=False)), ('abstract', wagtail.blocks.TextBlock(help_text='Leave empty to set from EUMETVIEW Layer details', label='Layer Abstract', required=False)), ('generate_animation_images', wagtail.blocks.BooleanBlock(default=False, label='Automatically generate animation images', required=False))], label='MSG Layer'))], blank=True, null=True, use_json_field=True, verbose_name='MSG Layers'),
        ),
    ]
