# Generated by Django 4.1.5 on 2023-02-02 13:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID. Auto generated on creation.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='City Name')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='City Location')),
            ],
            options={
                'verbose_name': 'City Information',
                'verbose_name_plural': 'City Information',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Forecasts Date')),
                ('max_temp', models.IntegerField(verbose_name='Maximum Temperature')),
                ('min_temp', models.IntegerField(verbose_name='Minimum Temperaure')),
                ('wind_direction', models.IntegerField(verbose_name='Wind Direction')),
                ('wind_speed', models.IntegerField(verbose_name='Wind Speed')),
                ('condition', models.CharField(max_length=255, null=True, verbose_name='Weather Condition')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast_manager.city')),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
            },
        ),
    ]
