# Generated by Django 4.1.7 on 2023-03-22 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditioncategory',
            name='short_name',
            field=models.CharField(blank=True, editable=False, help_text='Weather Condition Short Name (helpgul for yr.no weather api)', max_length=50, null=True, verbose_name='Weather Condtion Short Name'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='condition',
            field=models.ForeignKey(help_text='E.g Light Showers', null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast_manager.conditioncategory', verbose_name='General Weather Condition'),
        ),
    ]
