# Generated by Django 4.1.5 on 2023-02-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='condition',
            field=models.CharField(blank=True, help_text='E.g Light Showers', max_length=255, null=True, verbose_name='General Weather Condition'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='max_temp',
            field=models.IntegerField(blank=True, verbose_name='Maximum Temperature'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='min_temp',
            field=models.IntegerField(blank=True, verbose_name='Minimum Temperaure'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='wind_direction',
            field=models.IntegerField(blank=True, verbose_name='Wind Direction'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='wind_speed',
            field=models.IntegerField(blank=True, verbose_name='Wind Speed'),
        ),
    ]
