# Generated by Django 4.1.5 on 2023-02-02 14:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_manager', '0002_alter_forecast_condition_alter_forecast_max_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='City Location (Lat, Lng)'),
        ),
    ]
