# Generated by Django 4.1.7 on 2023-04-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_manager', '0003_measurementsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementSettings',
        ),
    ]
