# Generated by Django 4.1.7 on 2023-05-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('forecast_manager', '0004_delete_measurementsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditioncategory',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='conditioncategory',
            name='icon_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon image'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast_manager.city', verbose_name='City'),
        ),
    ]
