# Generated by Django 4.1.7 on 2023-03-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_manager', '0005_alter_forecast_wind_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='condition',
            field=models.CharField(blank=True, default='Light Showers', help_text='E.g Light Showers', max_length=255, verbose_name='General Weather Condition'),
        ),
    ]
