# Generated by Django 4.1.7 on 2023-03-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_manager', '0006_alter_forecast_condition'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(fields=('city', 'forecast_date'), name='Unique combination of city and forecast date'),
        ),
    ]
