# Generated by Django 4.1.7 on 2023-03-03 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('forecast_manager', '0007_forecast_unique combination of city and forecast date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Weather Condition Title', max_length=50, verbose_name='Weather Condtion Title')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ForeignKey(blank=True, help_text='An Icon representing the weather condtion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Weather Condition Icon')),
            ],
            options={
                'verbose_name': 'Weather Condition Category',
                'verbose_name_plural': 'Weather Condition Categories',
            },
        ),
        migrations.AlterField(
            model_name='forecast',
            name='condition',
            field=models.ForeignKey(help_text='E.g Light Showers', on_delete=django.db.models.deletion.CASCADE, to='forecast_manager.conditioncategory', verbose_name='General Weather Condition'),
        ),
    ]
