# Generated by Django 4.1.7 on 2023-03-03 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webicons', '0003_alter_webicon_id'),
        ('forecast_manager', '0009_alter_conditioncategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditioncategory',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webicons.webicon'),
        ),
    ]
