# Generated by Django 4.1.7 on 2023-03-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_manager', '0011_alter_conditioncategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='conditioncategory',
            name='title',
            field=models.CharField(help_text='Weather Condition Title', max_length=50, verbose_name='Weather Condtion Title'),
        ),
    ]
