# Generated by Django 4.1.7 on 2023-03-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('forecast_manager', '0012_alter_city_name_alter_conditioncategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioncategory',
            name='icon_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
