# Generated by Django 4.1.7 on 2023-03-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_manager', '0013_conditioncategory_icon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditioncategory',
            name='icon',
        ),
    ]
