# Generated by Django 3.2.20 on 2023-09-18 13:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtailiconchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicepage_feature_block_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='what_we_do_items',
            field=wagtail.fields.StreamField([('what_we_do', wagtail.blocks.StructBlock([('icon', wagtailiconchooser.blocks.IconChooserBlock(label='Icon', required=False)), ('title', wagtail.blocks.CharBlock(max_length=60, required=False)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4']))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
