# Generated by Django 4.2.18 on 2025-03-20 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publicationsindexpage_earliest_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationsindexpage',
            name='earliest_publication_year',
            field=models.PositiveIntegerField(default=2025, help_text='The year for the earliest available publication. This is used to generate the years available for filtering ', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)], verbose_name='Earliest Publication Year'),
        ),
    ]
