# Generated by Django 5.2.2 on 2026-02-09 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationsindexpage',
            name='earliest_publication_year',
            field=models.PositiveIntegerField(default=2026, help_text='The year for the earliest available publication. This is used to generate the years available for filtering ', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)], verbose_name='Earliest Publication Year'),
        ),
    ]
