files:
  - source: pages/data_request/locale/en/LC_MESSAGES/django.po
    translation: LC_MESSAGES/django.po
  - source: pages/email_subscription/locale/en/LC_MESSAGES/django.po
    translation: LC_MESSAGES/django.po
