files:
  - source: pages/data_request/locale/en/LC_MESSAGES/django.po
    translation: pages/data_request/locale/%two_letters_code%/LC_MESSAGES/django.po
  - source: pages/email_subscription/locale/en/LC_MESSAGES/django.po
    translation: pages/email_subscription/locale/%two_letters_code%/LC_MESSAGES/django.po
