project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_TOKEN

"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files:
  # Base & config
  - source: /climweb/src/climweb/base/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/base/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/config/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/config/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/cityclimate/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/cityclimate/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/contact/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/contact/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/data_request/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/data_request/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/email_subscription/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/email_subscription/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/events/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/events/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/feedback/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/feedback/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/flex_page/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/flex_page/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/glossary/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/glossary/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/home/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/home/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/mediacenter/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/mediacenter/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/news/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/news/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true


  # Organisation pages
  - source: /climweb/src/climweb/pages/organisation_pages/about/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/organisation_pages/about/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/organisation_pages/organisation/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/organisation_pages/organisation/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/organisation_pages/partners/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/organisation_pages/partners/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/organisation_pages/projects/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/organisation_pages/projects/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/organisation_pages/tenders/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/organisation_pages/tenders/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/organisation_pages/vacancies/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/organisation_pages/vacancies/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/organisation_pages/staff/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/organisation_pages/staff/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true


  # More pages
  - source: /climweb/src/climweb/pages/products/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/products/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/dashboards/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/dashboards/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/publications/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/publications/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/satellite_imagery/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/satellite_imagery/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/search/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/search/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/services/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/services/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/stations/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/stations/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/surveys/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/surveys/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/videos/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/videos/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/wdqms/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/wdqms/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /climweb/src/climweb/pages/weather/locale/en/LC_MESSAGES/django.po
    translation: /climweb/src/climweb/pages/weather/locale/%two_letters_code%/LC_MESSAGES/django.po
    skip_untranslated_strings: true
    export_translated_only: true

    # docs translations 

  - source: /docs/locale/en/LC_MESSAGES/_docs.po
    translation: /docs/locale/%two_letters_code%/LC_MESSAGES/_docs.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /docs/locale/en/LC_MESSAGES/index.po
    translation: /docs/locale/%two_letters_code%/LC_MESSAGES/index.po
    skip_untranslated_strings: true
    export_translated_only: true

  - source: /docs/locale/en/LC_MESSAGES/sphinx.po
    translation: /docs/locale/%two_letters_code%/LC_MESSAGES/sphinx.po
    skip_untranslated_strings: true
    export_translated_only: true
  
