# Generated by Django 4.1.9 on 2023-05-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('webicons', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webicons.webicon', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.application'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecategory'),
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webicons.webicon', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='all_alerts_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All alerts page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='all_applications_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All applications page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='all_events_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All events page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='all_news_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All news page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='all_partners_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All partners page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='all_products_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All products page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='all_projects_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All projects page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='all_publications_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All publications page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='all_tenders_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All tenders page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='all_vacancies_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All vacancies page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='all_videos_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All videos page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='contact_us_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Contact us page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='feedback_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All feedback page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='mailing_list_signup_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Mailing list sign up page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webicons.webicon', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Thumbnail/image for this type of event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='application',
            name='services',
            field=models.ManyToManyField(related_name='applications', through='core.ServiceApplication', to='core.servicecategory', verbose_name='Services'),
        ),
        migrations.AddField(
            model_name='application',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceapplication',
            unique_together={('service', 'application')},
        ),
    ]
