# Generated by Django 4.1.7 on 2023-02-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productcategory_servicecategory_publicationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_alert', models.BooleanField(default=False)),
                ('is_press_release', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'News Type',
                'verbose_name_plural': 'News Types',
            },
        ),
    ]
