# Generated by Django 4.1.7 on 2023-02-28 14:21

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('core', '0003_newstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('show_in_geoportal', models.BooleanField(default=False, help_text='Show in geoportal.nmhs.net applications section', verbose_name='Show in Geoportal apps section - geoportal.nmhs.net')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'GIS Application',
                'verbose_name_plural': 'GIS Applications',
            },
        ),
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.application')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecategory')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('service', 'application')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='services',
            field=models.ManyToManyField(related_name='applications', through='core.ServiceApplication', to='core.servicecategory'),
        ),
        migrations.AddField(
            model_name='application',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
