# Generated by Django 4.1.9 on 2023-06-12 17:06

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_productitemtype_remove_producttype_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='core.product', verbose_name='Product'),
        ),
    ]
