# Generated by Django 4.1.7 on 2023-02-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_application_serviceapplication_application_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='show_in_geoportal',
        ),
    ]
