# Generated by Django 4.1.7 on 2023-02-28 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webicons', '0003_alter_webicon_id'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('core', '0005_remove_application_show_in_geoportal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webicons.webicon')),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Thumbnail/image for this type of event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
