# Generated by Django 4.1.7 on 2023-03-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_importantpages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importantpages',
            old_name='all_cropmonitors_page',
            new_name='all_products_page',
        ),
    ]
