# Generated by Django 4.1.7 on 2023-03-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_all_cropmonitors_page_importantpages_all_products_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importantpages',
            name='all_foodsecuritystatements_page',
        ),
        migrations.RemoveField(
            model_name='importantpages',
            name='all_monthly_forecasts_page',
        ),
        migrations.RemoveField(
            model_name='importantpages',
            name='all_seasonal_forecasts_page',
        ),
        migrations.RemoveField(
            model_name='importantpages',
            name='all_weekly_forecasts_page',
        ),
        migrations.RemoveField(
            model_name='importantpages',
            name='data_center_page',
        ),
        migrations.RemoveField(
            model_name='importantpages',
            name='rcc_page',
        ),
    ]
