# Generated by Django 4.1.7 on 2023-03-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '0009_remove_importantpages_all_foodsecuritystatements_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantpages',
            name='all_alerts_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
