# Generated by Django 4.1.7 on 2023-03-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webicons', '0004_alter_webicon_file'),
        ('core', '0012_remove_importantpages_all_forecasts_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webicons.webicon'),
        ),
    ]
