# Generated by Django 4.1.7 on 2023-04-07 09:15

import django.core.validators
from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_servicecategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', wagtail_color_panel.fields.ColorField(blank=True, default='#363636', help_text='Primary color', max_length=7, null=True)),
                ('secondary_color', wagtail_color_panel.fields.ColorField(blank=True, default='#3488ce', help_text='Secondary color', max_length=7, null=True)),
                ('border_radius', models.IntegerField(help_text='Minimum 0 and Maximum 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
