# Generated by Django 4.1.7 on 2023-04-07 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_theme_border_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='border_radius',
            field=models.IntegerField(default=4, help_text='Minimum 0 and Maximum 100 in percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
