# Generated by Django 4.1.7 on 2023-04-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_theme_border_radius_alter_theme_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Theme Name'),
        ),
    ]
