# Generated by Django 4.1.7 on 2023-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_theme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, help_text='Enable if this is the default theme', null=True, verbose_name='Is default Theme'),
        ),
    ]
