# Generated by Django 4.1.7 on 2023-04-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_theme_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Enable if this is the default theme', verbose_name='Is default Theme'),
        ),
    ]
