# Generated by Django 4.1.7 on 2023-04-07 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_theme_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='border_radius',
            field=models.IntegerField(default=4, help_text='Minimum 0 and Maximum 100 in percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Border radius (px)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Enable if this is the default theme', verbose_name='Is Default Theme'),
        ),
    ]
