# Generated by Django 4.1.7 on 2023-04-07 13:23

import django.core.validators
from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_theme_border_radius_alter_theme_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='bs_blur_rad',
            field=models.IntegerField(default=1, help_text='Minimum 0 and Maximum 100 in percentage', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Blur radius (px)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='bs_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#3488ce', help_text='Box shadow color (use color picker)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='bs_color_opacity',
            field=models.DecimalField(decimal_places=2, default=0.125, help_text='Minimum 0 and Maximum 100 in percentage', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Color opacity'),
        ),
        migrations.AddField(
            model_name='theme',
            name='bs_hr_off',
            field=models.IntegerField(default=0, help_text='Minimum 0 and Maximum 100 in percentage', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Horizontal Offset (px)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='bs_spread_rad',
            field=models.IntegerField(default=-0.125, help_text='Minimum 0 and Maximum 100 in percentage', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Spread radius (px)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='bs_vt_off',
            field=models.IntegerField(default=0.5, help_text='Minimum 0 and Maximum 100 in percentage', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Vertical Offset (px)'),
        ),
    ]
