# Generated by Django 4.1.7 on 2023-04-07 13:24

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_theme_bs_blur_rad_theme_bs_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='bs_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#363636', help_text='Box shadow color (use color picker)', max_length=7, null=True),
        ),
    ]
