# Generated by Django 4.1.7 on 2023-04-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_theme_secondary_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
