# Generated by Django 4.1.7 on 2023-05-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('webicons', '0004_alter_webicon_file'),
        ('core', '0025_delete_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Event Type'},
        ),
        migrations.AlterField(
            model_name='application',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='application',
            name='services',
            field=models.ManyToManyField(related_name='applications', through='core.ServiceApplication', to='core.servicecategory', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='application',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_type',
            field=models.CharField(max_length=255, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webicons.webicon', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='all_alerts_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All alerts page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='all_applications_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All applications page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='all_events_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All events page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='all_news_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All news page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='all_partners_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All partners page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='all_products_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All products page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='all_projects_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All projects page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='all_publications_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All publications page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='all_tenders_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All tenders page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='all_vacancies_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All vacancies page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='all_videos_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All videos page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='contact_us_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Contact us page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='feedback_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All feedback page'),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='mailing_list_signup_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Mailing list sign up page'),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='is_alert',
            field=models.BooleanField(default=False, verbose_name='Is alert'),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='is_press_release',
            field=models.BooleanField(default=False, verbose_name='Is press release'),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publicationtype',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webicons.webicon', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='publicationtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webicons.webicon', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
