# Generated by Django 4.2.3 on 2023-10-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0004_alter_mediaindexpage_feature_block_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaindexpage',
            name='introduction_button_link_external',
            field=models.URLField(blank=True, help_text='External Link if applicable. Ignored if internal page above is chosen', null=True),
        ),
    ]
