# Generated by Django 4.1.7 on 2023-02-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationpage',
            name='show_in_rcc',
        ),
    ]
