# Generated by Django 4.1.7 on 2023-03-01 22:41

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectpage_partners'),
        ('publications', '0002_remove_publicationpage_show_in_rcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='projects',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='projects.projectpage', verbose_name='Relevant Projects'),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='show_in_rcc',
            field=models.BooleanField(default=False, help_text='Should this appear in the RCC page ?'),
        ),
    ]
