# Generated by Django 4.1.7 on 2023-03-01 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publicationpage_projects_publicationpage_show_in_rcc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationpage',
            name='show_in_rcc',
        ),
    ]
