# Generated by Django 4.1.7 on 2023-05-02 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '0026_alter_eventtype_options_alter_application_order_and_more'),
        ('publications', '0004_remove_publicationpage_show_in_rcc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationsindexpage',
            options={'verbose_name': 'Publications Index Page'},
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='is_visible_on_homepage',
            field=models.BooleanField(default=False, help_text='Should this appear in the homepage as an alert/latest update ?', verbose_name='Is visible on homepage'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='peer_reviewed',
            field=models.BooleanField(default=False, help_text='Is this a peer reviewed publication ?', verbose_name='Peer reviewed'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='period_end_date',
            field=models.DateField(blank=True, help_text='Optional end date for which this publication is relevant', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='period_start_date',
            field=models.DateField(blank=True, help_text='Optional start date for which this publication is relevant', null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='publication_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.publicationtype', verbose_name='Publication Type'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='summary',
            field=wagtail.fields.RichTextField(verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='publicationsindexpage',
            name='banner_subtitle',
            field=models.CharField(max_length=255, verbose_name='Banner Subtitle'),
        ),
        migrations.AlterField(
            model_name='publicationsindexpage',
            name='banner_title',
            field=models.CharField(max_length=255, verbose_name='Banner Title'),
        ),
        migrations.AlterField(
            model_name='publicationsindexpage',
            name='call_to_action_button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text'),
        ),
        migrations.AlterField(
            model_name='publicationsindexpage',
            name='call_to_action_related_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page'),
        ),
        migrations.AlterField(
            model_name='publicationsindexpage',
            name='earliest_publication_year',
            field=models.PositiveIntegerField(default=2023, help_text='The year for the earliest available publication. This is used to generate the years available for filtering ', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2023)], verbose_name='Earliest Publication Year'),
        ),
    ]
