# Generated by Django 4.2.3 on 2023-11-09 07:54

from django.db import migrations, models
import django.db.models.deletion
import geomanager.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.JSONField(blank=True, null=True)),
                ('geom_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bounds', geomanager.fields.ListField(blank=True, max_length=256, null=True)),
                ('name_column', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
