# Generated by Django 4.0.10 on 2023-02-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webicons', '0002_webicon_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webicon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
