# Generated by Django 4.2.3 on 2024-02-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailchimpmailinglistsubscriptionpage',
            name='success_redirect_page',
        ),
        migrations.AlterField(
            model_name='mailchimpmailinglistsubscriptionpage',
            name='thank_you_text',
            field=models.TextField(blank=True, default='You have been successfully added to our mailing list. Thank you!', help_text='Message to show on successful submission', null=True, verbose_name='Thank you text'),
        ),
    ]
