# Generated by Django 5.2.14 on 2026-06-10 10:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newspage_feature_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='media_gallery',
            field=wagtail.fields.StreamField([('gallery', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional heading displayed above the gallery', 'label': 'Gallery title', 'max_length': 255, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption or image source credit', 'label': 'Caption', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Images', 'min_num': 1}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid', 'Uniform Grid – all images same height'), ('masonry', 'Masonry – images keep natural proportions')], 'label': 'Layout style'}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 columns'), ('3', '3 columns'), ('4', '4 columns')], 'label': 'Columns'}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('images', 4), ('grid_style', 5), ('columns', 6)]], {})}, null=True, verbose_name='Image Gallery'),
        ),
    ]
