# Generated by Django 5.2.14 on 2026-06-10 10:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_add_media_gallery_to_newspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='media_gallery',
            field=wagtail.fields.StreamField([('gallery', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional heading displayed above the gallery', 'label': 'Gallery title', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid', 'Uniform Grid – all images same height'), ('masonry', 'Masonry – images keep natural proportions')], 'label': 'Layout style'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 columns'), ('3', '3 columns'), ('4', '4 columns')], 'label': 'Columns'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption or image source credit', 'label': 'Caption', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Images', 'min_num': 1}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('grid_style', 1), ('columns', 2), ('images', 6)]], {})}, null=True, verbose_name='Image Gallery'),
        ),
    ]
