# Generated by Django 4.1.7 on 2023-02-28 13:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('core', '0003_newstype'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Post date')),
                ('subtitle', models.TextField(blank=True, help_text='Optional subtitle', null=True)),
                ('body', wagtail.fields.RichTextField()),
                ('feature_img_src', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Should this news appear on the news landing paging as the featured one ?')),
                ('is_alert', models.BooleanField(default=False, help_text='Is this an alert ?')),
                ('is_visible_on_homepage', models.BooleanField(default=False, help_text='Should this appear in the homepage as an alert/latest update ?')),
                ('extra_links_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('external_links', wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('link', wagtail.blocks.URLBlock(max_length=255))]))], blank=True, null=True, use_json_field=None)),
                ('news_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.newstype')),
                ('services', modelcluster.fields.ParentalManyToManyField(blank=True, to='core.servicecategory', verbose_name='Relevant Services')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_tags', to='news.newspage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newspage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.NewsPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(max_length=255)),
                ('banner_subtitle', models.CharField(max_length=255)),
                ('call_to_action_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('items_per_page', models.PositiveIntegerField(default=6, help_text='How many items should be visible on the news landing page filter section ?', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(20)])),
                ('banner_image', models.ForeignKey(blank=True, help_text='A high quality image related to News', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('call_to_action_related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
