# Generated by Django 4.1.7 on 2023-03-04 21:30

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectpage_partners'),
        ('news', '0002_alter_newspage_external_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='projects',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='projects.projectpage', verbose_name='Relevant Projects'),
        ),
    ]
