# Generated by Django 4.2.3 on 2023-08-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='name',
            field=models.CharField(help_text='Location of organisation', max_length=255, null=True, unique=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='location',
            field=models.CharField(help_text='Coordninates of organisation', max_length=250, null=True, verbose_name='Coordninates of organisation'),
        ),
    ]
