# Generated by Django 4.2.3 on 2023-10-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpage_name_alter_contactpage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='location',
            field=models.CharField(help_text='Coordinates of organisation', max_length=250, null=True, verbose_name='Coordinates of organisation'),
        ),
    ]
