# Generated by Django 4.2.2 on 2023-06-16 12:49

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerspage',
            name='partners_cta_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Call to action description text', null=True, verbose_name='Partners call to action text'),
        ),
        migrations.AlterField(
            model_name='partnerspage',
            name='partners_cta_title',
            field=models.CharField(blank=True, help_text='Partners call to action section title', max_length=100, null=True, verbose_name='Partners Call to Action title'),
        ),
    ]
