# Generated by Django 5.2.14 on 2026-07-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_tenderdetailpage_apply_fields'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderdetailpage',
            name='application_page',
            field=models.ForeignKey(blank=True, help_text='Select the page where applicants should submit their application, e.g. a Flexible Form page set up to collect applications. If left blank, the external link below is used instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Application Page'),
        ),
        migrations.AlterField(
            model_name='tenderdetailpage',
            name='external_application_url',
            field=models.URLField(blank=True, help_text='External link to apply, e.g. a link to an external HR or procurement system. Ignored if an application page is chosen above.', max_length=500, null=True, verbose_name='External Application Link'),
        ),
    ]
