# Generated by Django 4.1.7 on 2023-02-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0003_alertlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='area_desc',
            field=models.TextField(blank=True, help_text='The text describing the affected area of the alert message', null=True, verbose_name='Affected areas / Regions'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('geo', 'Geophysical'), ('met', 'Meteorological'), ('safety', 'General emergency and public safety'), ('security', 'Law enforcement, military, homeland and local/private security'), ('rescue', 'Rescue and recovery'), ('fire', 'Fire suppression and rescue'), ('health', 'Medical and public health'), ('env', 'Pollution and other environmental'), ('transport', 'Public and private transportation'), ('infra', 'Utility, telecommunication, other non-transport infrastructure'), ('cbrne', 'Chemical, Biological, Radiological, Nuclear or High-Yield Explosive threat or attack'), ('other', 'Other events')], default='met', help_text='The code denoting the category of the subject event of the alert message', max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='certainty',
            field=models.CharField(choices=[('observed', 'Observed - Determined to have occurred or to be ongoing'), ('likely', 'Likely - Likely (percentage > ~50%)'), ('possible', 'Possible - Possible but not likely (percentage <= ~50%)'), ('unlikely', 'Unlikely - Not expected to occur (percentage ~ 0)'), ('unknown', 'Unknown - Certainty unknown')], default='likely', help_text='The code denoting the certainty of the subject event of the alert message', max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='event',
            field=models.CharField(blank=True, help_text='The text denoting the type of the subject event of the alert message', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message_type',
            field=models.CharField(choices=[('alert', 'Alert - Initial information requiring attention by targeted recipients'), ('update', 'Update - Updates and supercedes the earlier message(s) identified in referenced alerts'), ('cancel', 'Cancel - Cancels the earlier message(s) identified in references'), ('ack', 'Acknowledge - Acknowledges receipt and acceptance of the message(s) identified in references field'), ('error', 'Error -  Indicates rejection of the message(s) identified in references; explanation SHOULD appear in note field')], default='alert', help_text='The code denoting the nature of the alert message', max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='scope',
            field=models.CharField(choices=[('public', 'Public - For general dissemination to unrestricted audiences'), ('restricted', 'Restricted - For dissemination only to users with a known operational requirement as in the restriction field'), ('private', 'Private - For dissemination only to specified addresses as in the addresses field in the alert')], default='public', help_text='The code denoting the intended distribution of the alert message', max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='sender',
            field=models.EmailField(default='grace@gmail.com', help_text=' Identifies the originator of an alert. This can be an email of the institution for example', max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('extreme', 'Extreme - Extraordinary threat to life or property'), ('severe', 'Severe - Significant threat to life or property'), ('moderate', 'Moderate - Possible threat to life or property'), ('minor', 'Minor - Minimal to no known threat to life or property'), ('unknown', 'Unknown - Severity unknown')], default='extreme', help_text='The code denoting the severity of the subject event of the alert message', max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - A preliminary template or draft, not actionable in its current form'), ('actual', 'Actual - Actionable by all targeted recipients'), ('test', 'Test - Technical testing only, all recipients disregard'), ('exercise', 'Exercise - Actionable only by designated exercise participants; exercise identifier SHOULD appear in note'), ('system', 'System - For messages that support alert network internal functions')], default='actual', help_text='The code denoting the appropriate handling of the alert', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='urgency',
            field=models.CharField(choices=[('immediate', 'Immediate - Responsive action SHOULD be taken immediately'), ('expected', 'Expected - Responsive action SHOULD be taken soon (within next hour)'), ('future', 'Future - Responsive action SHOULD be taken in the near future'), ('past', 'Past - Responsive action is no longer required'), ('unknown', 'Unknown - Urgency not known')], default='immediate', help_text='The code denoting the urgency of the subject event of the alert message', max_length=100),
        ),
    ]
