# Generated by Django 4.1.7 on 2023-02-22 08:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0004_alert_location_alter_alert_area_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_desc', models.CharField(help_text='The text describing the affected area of the alert message', max_length=100, verbose_name='Affected areas / Regions')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(help_text='The paired values of points defining a polygon that delineates the affected area of the alert message', srid=4326)),
                ('circle', django.contrib.gis.db.models.fields.PolygonField(help_text='The paired values of a point and radius delineating the affected area of the alert message', srid=4326)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_area', to='capeditor.alert')),
            ],
        ),
        migrations.RemoveField(
            model_name='alertpolygon',
            name='alert',
        ),
        migrations.DeleteModel(
            name='AlertCircle',
        ),
        migrations.DeleteModel(
            name='AlertPolygon',
        ),
    ]
