# Generated by Django 4.1.7 on 2023-02-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0005_alertarea_remove_alertpolygon_alert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='area_desc',
        ),
    ]
