# Generated by Django 4.1.7 on 2023-02-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0006_remove_alert_area_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertarea',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_areas', to='capeditor.alert'),
        ),
    ]
