# Generated by Django 4.1.7 on 2023-02-22 11:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0007_alter_alertarea_alert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertarea',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='alertarea',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='alertarea',
            name='alert',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_areas', to='capeditor.alert'),
        ),
    ]
