# Generated by Django 4.1.7 on 2023-02-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0008_alter_alertarea_options_alertarea_sort_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertarea',
            name='circle',
        ),
        migrations.RemoveField(
            model_name='alertarea',
            name='polygon',
        ),
        migrations.AddField(
            model_name='alertarea',
            name='area',
            field=models.CharField(help_text='The paired values of points defining a polygon that delineates the affected area of the alert message', max_length=250, null=True),
        ),
    ]
