# Generated by Django 4.1.7 on 2023-02-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0009_remove_alertarea_circle_remove_alertarea_polygon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='location',
        ),
        migrations.AlterField(
            model_name='alertarea',
            name='area',
            field=models.CharField(help_text='The paired values of points defining a polygon that delineates the affected area of the alert message', max_length=250, null=True, verbose_name='Area Geometry'),
        ),
    ]
