# Generated by Django 4.1.7 on 2023-02-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0011_alter_alertarea_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertarea',
            name='area',
            field=models.CharField(help_text='The paired values of points defining a polygon that delineates the affected area of the alert message', max_length=250, null=True, verbose_name='Area Geometry'),
        ),
    ]
