# Generated by Django 4.1.7 on 2023-02-23 08:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0013_alter_alertarea_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertarea',
            name='alert',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_areas', to='capeditor.alert'),
        ),
        migrations.AlterField(
            model_name='alertarea',
            name='area_desc',
            field=models.CharField(help_text='The text describing the affected area of the alert message', max_length=100, null=True, verbose_name='Affected areas / Regions'),
        ),
    ]
