# Generated by Django 4.1.7 on 2023-02-23 14:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0014_alter_alertarea_alert_alter_alertarea_area_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertarea',
            name='test_area',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
