# Generated by Django 4.1.7 on 2023-02-23 14:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0015_alertarea_test_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertarea',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='The paired values of points defining a polygon that delineates the affected area of the alert message', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='alertarea',
            name='area_desc',
            field=models.CharField(blank=True, help_text='The text describing the affected area of the alert message', max_length=100, null=True, verbose_name='Affected areas / Regions'),
        ),
    ]
