# Generated by Django 4.1.7 on 2023-02-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0016_alter_alertarea_area_alter_alertarea_area_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertarea',
            name='test_area',
        ),
    ]
