# Generated by Django 4.1.7 on 2023-02-28 14:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('services', '0002_servicepage_banner_image_servicepage_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='A high quality image related to this Service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='introduction_image',
            field=models.ForeignKey(blank=True, help_text='A high quality image related to this Service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Introduction Image'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='introduction_text',
            field=wagtail.fields.RichTextField(help_text='A description of what ORG does under  this Service', null=True),
        ),
    ]
