# Generated by Django 4.1.7 on 2023-02-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_servicepage_servicespage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicespage',
            name='what_we_do_items',
        ),
    ]
