# Generated by Django 4.1.7 on 2023-03-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_serviceindexpage_what_we_do_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceindexpage',
            name='what_we_do_items',
        ),
    ]
