# Generated by Django 4.1.7 on 2023-05-02 12:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('core', '0025_delete_theme'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('services', '0013_remove_serviceindexpage_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Service Page',
                'verbose_name_plural': 'Service Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='serviceindexpage',
            options={'verbose_name': 'Service Page', 'verbose_name_plural': 'Service Pages'},
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='A high quality image related to this Service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='banner_subtitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Banner Subtitle'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='banner_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Banner Title'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='call_to_action_button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='call_to_action_external_link',
            field=models.URLField(blank=True, help_text='External Link if applicable', null=True, verbose_name='Call to action external link'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='call_to_action_related_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='feature_block_items',
            field=wagtail.fields.StreamField([('feature_item', wagtail.blocks.StructBlock([('figure_type', wagtail.blocks.ChoiceBlock(choices=[('image', 'Image'), ('chart', 'Chart'), ('video', 'Video'), ('imageofchange', 'Image of Change')])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('chart_config_url', wagtail.blocks.URLBlock(help_text='A URL that returns Highcharts.js configuration, including the data', required=False)), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock(label='Description')), ('action_link_text', wagtail.blocks.CharBlock(max_length=15, required=False)), ('action_link', wagtail.blocks.PageChooserBlock(label='Action Link Internal', required=False)), ('action_link_external', wagtail.blocks.URLBlock(help_text='An external link to a detailed resource on the internet.If provided, the internal link will be ignored', max_length=400, required=False))]))], blank=True, null=True, use_json_field=True, verbose_name='Feature block items'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='introduction_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Introduction button link'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='introduction_button_link_external',
            field=models.URLField(blank=True, help_text='External Link if applicable. Ignored if internal page above is chosen', null=True, verbose_name='Introduction button link external'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='introduction_button_text',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Introduction button text'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='introduction_image',
            field=models.ForeignKey(blank=True, help_text='A high quality image related to this Service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Introduction Image'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='introduction_text',
            field=wagtail.fields.RichTextField(help_text='A description of what ORG does under  this Service', null=True),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='introduction_title',
            field=models.CharField(help_text='Introduction section title', max_length=100, null=True, verbose_name='Introduction title'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='projects_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Projects description text', null=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='what_we_do_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='What we do button link'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='what_we_do_button_text',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='What we do button text'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='youtube_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.youtubeplaylist', verbose_name='Youtube playlist'),
        ),
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
