# Generated by Django 4.1.7 on 2023-05-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('services', '0015_servicepage_remove_serviceindexpage_banner_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceIndexPage',
            new_name='ServiceListPage',
        ),
    ]
