# Generated by Django 4.1.7 on 2023-05-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_theme'),
        ('videos', '0001_initial'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('services', '0016_rename_serviceindexpage_servicelistpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicePage',
            new_name='ServiceIndexPage',
        ),
        migrations.RenameModel(
            old_name='ServiceListPage',
            new_name='ServicesPage',
        ),
    ]
