# Generated by Django 4.1.7 on 2023-05-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_rename_servicepage_serviceindexpage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicespage',
            options={'verbose_name': 'Service Index Page', 'verbose_name_plural': 'Service Index Pages'},
        ),
    ]
