# Generated by Django 4.2.18 on 2025-02-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('cityclimate', '0002_alter_dataparameter_chart_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityclimatedatapage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image'),
        ),
    ]
