# Generated by Django 4.1.8 on 2023-04-16 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MauticSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mautic_base_url', models.URLField(blank=True, help_text='Your Mautic site URL including the https:// prefix - do NOT add a trailing slash', null=True)),
                ('mautic_client_id', models.CharField(blank=True, help_text='Mautic Client ID. Obtain from Mautic Settings', max_length=256, null=True)),
                ('mautic_client_secret', models.CharField(blank=True, help_text='Mautic Client Secret. Obtain from Mautic Settings', max_length=256, null=True)),
                ('mautic_username', models.CharField(blank=True, help_text='Mautic username. Add if not using client ID and secret', max_length=256, null=True)),
                ('mautic_password', models.CharField(blank=True, help_text='Mautic Password. Add if not using client ID and client secret. Will not be visible once saved. Saving again will override any previously saved password', max_length=256, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
