# Generated by Django 4.2.2 on 2023-06-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindexpage',
            name='listing_heading',
            field=models.CharField(default='Explore our Products', max_length=255, verbose_name='Products listing Heading'),
        ),
    ]
