# Generated by Django 4.2.3 on 2023-08-28 07:35

import wagtail.blocks
import wagtail.fields
from django.db import migrations

from climweb.base.blocks import UUIDModelChooserBlock


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_alter_productitempage_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='map_layers',
            field=wagtail.fields.StreamField([('layers', wagtail.blocks.StructBlock(
                [('name', wagtail.blocks.CharBlock(required=False)), ('geomanager_layer',
                                                                      UUIDModelChooserBlock(
                                                                          target_model='geomanager.rasterfilelayer'))],
                label='Layer'))], blank=True, null=True, use_json_field=True, verbose_name='Map Layers'),
        ),
    ]
