# Generated by Django 4.2.3 on 2023-08-30 09:51

from django.db import migrations, models
import django.utils.timezone
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productpage_map_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitempage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='First date when products added below are effective', verbose_name='Effective date'),
        ),
        migrations.AlterField(
            model_name='productitempage',
            name='products',
            field=wagtail.fields.StreamField([('image_product', wagtail.blocks.StructBlock([('product_type', wagtail.blocks.CharBlock(label='Product Type', required=True)), ('date', wagtail.blocks.DateBlock(help_text='First effective date of the product', label='Effective date', required=True)), ('valid_until', wagtail.blocks.DateBlock(help_text='Last day when the product is effective', label='Effective until', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image', required=True)), ('description', wagtail.blocks.RichTextBlock(label='Summary of the map/image information'))], label='Map/Image Product')), ('document_product', wagtail.blocks.StructBlock([('product_type', wagtail.blocks.CharBlock(label='Product Type', required=True)), ('thumbnail', wagtail.images.blocks.ImageChooserBlock(help_text='For example a screen grab of the cover page', label='Thumbnail of the document', required=False)), ('date', wagtail.blocks.DateBlock(label='Product date', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True)), ('description', wagtail.blocks.RichTextBlock(label='Summary of the document information'))], label='Document/Bulletin Product'))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='productitempage',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Up to when are product added below effective ? Leave blank if not applicable', null=True, verbose_name='Effective until'),
        ),
    ]
