# Generated by Django 4.2.7 on 2024-07-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_subnationalregion_alter_productpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='menu_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Menu Order'),
        ),
        migrations.AddField(
            model_name='subnationalproductpage',
            name='menu_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Menu Order'),
        ),
    ]
