# Generated by Django 4.2.18 on 2025-04-16 07:26

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_productpage_introduction_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitempage',
            name='products',
            field=wagtail.fields.StreamField([('image_product', 5), ('document_product', 10), ('content_block', 14)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Product Type', 'required': True}), 1: ('wagtail.blocks.DateBlock', (), {'help_text': 'The date when this product becomes effective', 'label': 'Effective from', 'required': True}), 2: ('wagtail.blocks.DateBlock', (), {'help_text': 'The last day this product remains effective. Leave blank if not applicable', 'label': 'Effective until', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Summary of the map/image information', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('product_type', 0), ('date', 1), ('valid_until', 2), ('image', 3), ('description', 4)]], {'label': 'Map/Image Product'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': True}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'If the document is a PDF, an image of the first page will be auto-generated.', 'label': 'Auto-generate thumbnail', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'For example a screen grab of the cover page. If left empty and Auto-generate above is checked and the uploaded document is a PDF, an image of the first page will be auto-generated.', 'label': 'Thumbnail of the document', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Summary of the document information', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('product_type', 0), ('date', 1), ('valid_until', 2), ('document', 6), ('auto_generate_thumbnail', 7), ('thumbnail', 8), ('description', 9)]], {'label': 'Document/Bulletin Product'}), 11: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Table', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', 'mergeCells'], 'mergeCells': True}}), 12: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'}), 13: ('wagtail.blocks.StreamBlock', [[('table', 11), ('text', 12)]], {'label': 'Content'}), 14: ('wagtail.blocks.StructBlock', [[('product_type', 0), ('date', 1), ('valid_until', 2), ('content', 13)]], {'label': 'Text/Tabular Product'})}),
        ),
    ]
