# Generated by Django 5.2.12 on 2026-05-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_productingestedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingestedfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
