# Generated by Django 5.2.2 on 2026-06-10 14:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_productingestedfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitempage',
            name='products',
            field=wagtail.fields.StreamField([('image_product', 5), ('gif_product', 8), ('document_product', 13), ('content_block', 17)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Product Type', 'required': True}), 1: ('wagtail.blocks.DateBlock', (), {'help_text': 'The date when this product becomes effective', 'label': 'Effective from', 'required': True}), 2: ('wagtail.blocks.DateBlock', (), {'help_text': 'The last day this product remains effective. Leave blank if not applicable', 'label': 'Effective until', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Summary of the map/image information', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('product_type', 0), ('date', 1), ('valid_until', 2), ('image', 3), ('description', 4)]], {'label': 'Map/Image Product'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload a GIF file. Animated GIFs are supported.', 'label': 'GIF file', 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'label': 'Summary of the GIF information', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('product_type', 0), ('date', 1), ('valid_until', 2), ('gif', 6), ('description', 7)]], {'label': 'GIF Product'}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': True}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'If the document is a PDF, an image of the first page will be auto-generated.', 'label': 'Auto-generate thumbnail', 'required': False}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'For example a screen grab of the cover page. If left empty and Auto-generate above is checked and the uploaded document is a PDF, an image of the first page will be auto-generated.', 'label': 'Thumbnail of the document', 'required': False}), 12: ('wagtail.blocks.RichTextBlock', (), {'label': 'Summary of the document information', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('product_type', 0), ('date', 1), ('valid_until', 2), ('document', 9), ('auto_generate_thumbnail', 10), ('thumbnail', 11), ('description', 12)]], {'label': 'Document/Bulletin Product'}), 14: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Table', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', 'mergeCells'], 'mergeCells': True}}), 15: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'}), 16: ('wagtail.blocks.StreamBlock', [[('table', 14), ('text', 15)]], {'label': 'Content'}), 17: ('wagtail.blocks.StructBlock', [[('product_type', 0), ('date', 1), ('valid_until', 2), ('content', 16)]], {'label': 'Text/Tabular Product'})}),
        ),
    ]
