# Generated by Django 4.2.3 on 2024-02-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0009_merge_20231114_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capalertpage',
            options={'ordering': ['-sent']},
        ),
    ]
