# Generated by Django 4.2.7 on 2024-06-03 12:04

import capeditor.blocks
from django.db import migrations, models
import uuid
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0016_auto_20240530_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capalertpage',
            options={'ordering': ['-sent'], 'verbose_name': 'CAP Alert'},
        ),
        migrations.AlterField(
            model_name='capalertpage',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID. Auto generated on creation.', unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='capalertpage',
            name='msgType',
            field=models.CharField(choices=[('Alert', 'Alert - Initial information requiring attention by targeted recipients'), ('Update', 'Update - Updates and supersedes the earlier message(s) identified in referenced alerts'), ('Cancel', 'Cancel - Cancels the earlier message(s) identified in references')], default='Alert', help_text='The code denoting the nature of the alert message', max_length=100, verbose_name='Message Type'),
        ),
        migrations.AlterField(
            model_name='capalertpage',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft - A preliminary template or draft, not actionable in its current form'), ('Actual', 'Actual - Actionable by all targeted recipients'), ('Test', 'Test - Technical testing only, all recipients disregard'), ('Exercise', 'Exercise - Actionable only by designated exercise participants; exercise identifier SHOULD appear in note'), ('System', 'System - For messages that support alert network internal functions')], default='Actual', help_text='The code denoting the appropriate handling of the alert', max_length=50, verbose_name='Status'),
        ),
    ]
