# Generated by Django 4.1.7 on 2023-02-28 11:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '__first__'),
        ('webicons', '0003_alter_webicon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Posting')),
                ('duty_station', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField(verbose_name='Application Deadline')),
                ('description', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Job Description')),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.ForeignKey(blank=True, help_text='Optional downloadable job description document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customdocumentmodel', verbose_name='Downloadable Job Description Document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VacanciesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(max_length=255)),
                ('banner_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('introduction_title', models.CharField(help_text='Introduction section title', max_length=100)),
                ('introduction_text', wagtail.fields.RichTextField(help_text='A description of working at ORG')),
                ('introduction_button_text', models.TextField(blank=True, max_length=20, null=True)),
                ('items_per_page', models.PositiveIntegerField(default=6, help_text='How many items should be visible on the landing page filter section ?', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(20)])),
                ('no_vacancies_header_text', models.TextField(blank=True, help_text='Text to appear when there are no vacancies', null=True)),
                ('no_vacancies_description_text', models.TextField(blank=True, help_text='Additional text to appear when there are no vacancies,below the no vacancies header text', null=True)),
                ('banner_image', models.ForeignKey(blank=True, help_text='A high quality image related to Vacancies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('call_to_action_related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('introduction_button_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('introduction_image', models.ForeignKey(blank=True, help_text='A high quality illustration related to Working at ORG', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webicons.webicon', verbose_name='Vacancies SVG Illustration')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
