# Generated by Django 4.1.7 on 2023-05-02 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('vacancies', '0002_rename_vacanciesindexpage_vacanciespage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacanciespage',
            options={'verbose_name': 'Vacancy Page'},
        ),
        migrations.AlterModelOptions(
            name='vacancydetailpage',
            options={'verbose_name': 'Vacancy Detail Page'},
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner Subtitle'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='banner_title',
            field=models.CharField(max_length=255, verbose_name='Banner Title'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='call_to_action_button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='call_to_action_related_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='introduction_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Introduction button link'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='introduction_button_text',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Introduction button text'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='introduction_text',
            field=wagtail.fields.RichTextField(help_text='A description of working at ORG', verbose_name='Introduction text'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='introduction_title',
            field=models.CharField(help_text='Introduction section title', max_length=100, verbose_name='Introduction Title'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='items_per_page',
            field=models.PositiveIntegerField(default=6, help_text='How many items should be visible on the landing page filter section ?', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(20)], verbose_name='Items per page'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='no_vacancies_description_text',
            field=models.TextField(blank=True, help_text='Additional text to appear when there are no vacancies,below the no vacancies header text', null=True, verbose_name='No vacancies description text'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='no_vacancies_header_text',
            field=models.TextField(blank=True, help_text='Text to appear when there are no vacancies', null=True, verbose_name='No vacancies header text'),
        ),
        migrations.AlterField(
            model_name='vacancydetailpage',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='vacancydetailpage',
            name='duty_station',
            field=models.CharField(max_length=100, verbose_name='Duty Station'),
        ),
    ]
