# Generated by Django 4.1.9 on 2023-06-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacanciespage_search_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciespage',
            name='introduction_title',
            field=models.CharField(help_text='Introduction section title', max_length=100, verbose_name='Introduction Title'),
        ),
    ]
