# Generated by Django 4.2.7 on 2024-04-19 20:34

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationchartpage',
            name='introduction_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introduction section description', null=True, verbose_name='Introduction text'),
        ),
        migrations.AddField(
            model_name='organisationchartpage',
            name='introduction_title',
            field=models.CharField(blank=True, help_text='Introduction section title', max_length=100, null=True, verbose_name='Introduction Title'),
        ),
    ]
