# Generated by Django 4.2.7 on 2024-04-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0003_organisationchartpage_introduction_heading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '{name} ({role})', 'verbose_name_plural': '{name} ({role})'},
        ),
        migrations.AlterModelOptions(
            name='organisationchartpage',
            options={'verbose_name': 'Staff/Management Page'},
        ),
    ]
