# Generated by Django 4.2.7 on 2024-04-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0004_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['sort_order'], 'verbose_name': '{name} ({role})', 'verbose_name_plural': '{name} ({role})'},
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
