# Generated by Django 4.2.7 on 2024-04-21 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0005_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orgchart.department', verbose_name="Employee's Department"),
        ),
    ]
