# Generated by Django 4.2.3 on 2023-08-28 07:35

from django.db import migrations
import pages.products.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productitempage_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='map_layers',
            field=wagtail.fields.StreamField([('layers', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=False)), ('geomanager_layer', pages.products.models.UUIDModelChooserBlock(target_model='geomanager.fileimagelayer'))], label='Layer'))], blank=True, null=True, use_json_field=True, verbose_name='Map Layers'),
        ),
    ]
