# Generated by Django 4.2.3 on 2024-04-16 11:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_integrationsettings_google_site_verification_key'),
        ('products', '0022_alter_productitempage_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='other_services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='other_services', to='base.servicecategory', verbose_name='Other relevant Services'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.servicecategory', verbose_name='Primary Service'),
        ),
    ]
