# Generated by Django 5.2.1 on 2025-06-28 07:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(blank=True, max_length=255)),
                ('banner_description', models.TextField(blank=True)),
                ('banner_background_color', models.CharField(default='#ed6cd1', help_text='Hex color (e.g. #f5f5f5)', max_length=7)),
                ('body', wagtail.fields.StreamField([('text', 0)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'ul', 'ol']})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
