# Generated by Django 5.2.1 on 2025-09-11 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardgallerypage',
            options={'verbose_name': 'Dashboards Gallery / Atlas'},
        ),
        migrations.AddField(
            model_name='dashboardpage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image'),
        ),
    ]