# Generated by Django 5.2.2 on 2025-09-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardgallerypage',
            options={'verbose_name': 'Dashboards Gallery / Atlas'},
        ),
        migrations.AlterField(
            model_name='chartsnippet',
            name='area_desc',
            field=models.TextField(blank=True, help_text='Click on map to generate name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='admin_level',
            field=models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2')], default=0, help_text='Administrative Level'),
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='area_desc',
            field=models.TextField(blank=True, help_text='Click on map to generate name', max_length=50, null=True),
        ),
    ]
