# Generated by Django 5.2.1 on 2025-06-28 08:23

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardpage',
            options={'verbose_name': 'Dashboard Page'},
        ),
        migrations.AlterField(
            model_name='dashboardpage',
            name='banner_background_color',
            field=models.CharField(default='#f5f5f5', help_text='Hex color code for banner background (e.g., #ffffff)', max_length=7),
        ),
        migrations.AlterField(
            model_name='dashboardpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('line', 'Line Chart'), ('bar', 'Bar Chart')]}), 4: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'required': True, 'target_model': 'geomanager.Layer'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Field for X-axis (must match dataset field name)', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Field for Y-axis (must match dataset field name)', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('title', 1), ('description', 2), ('chart_type', 3), ('dataset', 4), ('x_field', 5), ('y_field', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('charts', 8)]], {})}),
        ),
    ]
