# Generated by Django 5.2.1 on 2025-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmap',
            name='selected_datetime',
            field=models.DateTimeField(help_text='If applicable, select the time slice to display for this dataset.', null=True, verbose_name='Selected Timestamp'),
        ),
    ]
