# Generated by Django 5.2.1 on 2025-07-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_alter_dashboardmap_selected_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardmap',
            name='selected_datetime',
        ),
    ]
