# Generated by Django 5.2.2 on 2025-09-22 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_alter_dashboardgallerypage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmap',
            name='geostore_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='dashboardmap',
            name='gid0',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmap',
            name='gid1',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmap',
            name='gid2',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
