# Generated by Django 5.2.2 on 2025-09-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_dashboardmap_geostore_id_dashboardmap_gid0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardmap',
            name='admin_path',
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='gid0',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='gid1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='gid2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]