# Generated by Django 5.2.1 on 2025-07-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_remove_dashboardmap_selected_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmap',
            name='selected_datetime',
            field=models.DateTimeField(help_text='Select the time slice to display for this dataset.', null=True, verbose_name='Selected Timestamp'),
        ),
    ]
