# Generated by Django 5.2.1 on 2025-06-28 08:52

import climweb.pages.dashboards.snippets
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alter_dashboardpage_body'),
        ('geomanager', '0052_remove_rasterstyle_rendering_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': climweb.pages.dashboards.snippets.ChartSnippet}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('charts', 2)]], {})}),
        ),
        migrations.CreateModel(
            name='ChartSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('chart_type', models.CharField(choices=[('line', 'Line Chart'), ('bar', 'Bar Chart')], default='line', max_length=10)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='geomanager.rasterfilelayer')),
            ],
        ),
    ]
