# Generated by Django 5.2.1 on 2025-07-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_dashboardmap_selected_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardmap',
            old_name='selected_datetime',
            new_name='selected_date',
        ),
    ]
