# Generated by Django 5.2.2 on 2025-09-22 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_remove_dashboardmap_admin_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartsnippet',
            name='admin_path',
        ),
        migrations.AddField(
            model_name='chartsnippet',
            name='geostore_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='chartsnippet',
            name='gid0',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='chartsnippet',
            name='gid1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='chartsnippet',
            name='gid2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
