# Generated by Django 5.2.1 on 2025-07-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_rename_selected_datetime_dashboardmap_selected_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardmap',
            name='selected_date',
        ),
    ]
