# Generated by Django 5.2.1 on 2025-06-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_dashboardpage_body_chartsnippet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartsnippet',
            options={'verbose_name': 'Dashboard Chart', 'verbose_name_plural': 'Dashboard Charts'},
        ),
    ]
