# Generated by Django 5.2.2 on 2025-10-03 10:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_remove_chartsnippet_admin_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpage',
            name='additional_materials',
            field=wagtail.fields.StreamField([('material', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('document', 'Document/File'), ('image', 'Image')]}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Select document or file', 'required': False, 'verbose_name': 'Document/File'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select/upload image', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('type', 1), ('title', 0), ('document', 2), ('image', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('category', 0), ('materials', 5)]], {})}, null=True, verbose_name='Additional Materials'),
        ),
        migrations.AlterField(
            model_name='chartsnippet',
            name='area_desc',
            field=models.TextField(blank=True, help_text='Click on map to generate name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='admin_level',
            field=models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2')], default=0, help_text='Administrative Level'),
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='area_desc',
            field=models.TextField(blank=True, help_text='Click on map to generate name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 25)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section Title', 'max_length': 100, 'verbose_name': 'Section Title'}), 2: ('wagtail.blocks.StructBlock', [[('title', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'code', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'hr', 'anchor', 'table', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull', 'indent', 'outdent', 'html'], 'help_text': 'Section description', 'verbose_name': 'Section Text'}), 4: ('wagtail.blocks.StructBlock', [[('text', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('text', 3)]], {'icon': 'document'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 1), ('text', 3), ('image', 6)]], {'icon': 'image'}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.ChartSnippet'}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('charts_block', 9)]], {}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.DashboardMap'}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('maps_block', 12)]], {}), 14: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': False, 'rowHeaders': False}}), 15: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 14)]], {'icon': 'table'}), 16: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'label': 'Icon', 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 18: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4']}), 19: ('wagtail.blocks.StructBlock', [[('icon', 16), ('title', 17), ('description', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Card button text', 'max_length': 20, 'required': False}), 22: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Card button link', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('what_we_do_items', 20), ('what_we_do_button_text', 21), ('what_we_do_button_link', 22)]], {}), 24: ('wagtail.blocks.StreamBlock', [[('title_only', 2), ('text_only', 4), ('title_text', 5), ('title_text_image', 7), ('chart', 10), ('map', 13), ('table', 15), ('what_we_do', 23)]], {'required': True}), 25: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('content', 24)]], {})}),
        ),
    ]
