# Generated by Django 5.2.2 on 2025-10-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_dashboardpage_additional_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmap',
            name='map_type',
            field=models.CharField(choices=[('single', 'Single Map'), ('comparison', 'Comparison Map')], default='single', help_text='Select whether this is a single map or a comparison map.', max_length=20),
        ),
    ]
