# Generated by Django 5.2.1 on 2025-06-28 09:26

import climweb.pages.dashboards.snippets
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_alter_chartsnippet_options'),
        ('geomanager', '0052_remove_rasterstyle_rendering_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': climweb.pages.dashboards.snippets.ChartSnippet}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': climweb.pages.dashboards.snippets.DashboardMap}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('charts', 2), ('maps', 4)]], {})}),
        ),
        migrations.CreateModel(
            name='DashboardMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='geomanager.rasterfilelayer')),
            ],
            options={
                'verbose_name': 'Dashboard Map',
                'verbose_name_plural': 'Dashboard Maps',
            },
        ),
    ]
