# Generated by Django 5.2.2 on 2025-09-26 11:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_dashboardpage_search_image_alter_dashboardpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpage',
            name='additional_materials',
            field=wagtail.fields.StreamField([('material', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('document', 'Document/File'), ('image', 'Image')]}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Select document or file', 'required': False, 'verbose_name': 'Document/File'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select/upload image', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('type', 1), ('title', 0), ('document', 2), ('image', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('category', 0), ('materials', 5)]], {})}, null=True, verbose_name='Additional Materials'),
        ),
    ]
