# Generated by Django 5.2.1 on 2025-07-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_remove_dashboardmap_selected_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardmap',
            options={},
        ),
        migrations.AlterField(
            model_name='chartsnippet',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line Chart'), ('column', 'Bar Chart'), ('stripes', 'Warming stripes')], default='line', max_length=10),
        ),
    ]
