# Generated by Django 5.2.1 on 2025-07-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_alter_dashboardmap_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardgallerypage',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
