# Generated by Django 5.2.1 on 2025-06-28 09:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_alter_dashboardpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.ChartSnippet'}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('charts_block', 2)]], {}), 4: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.DashboardMap'}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('maps_block', 5)]], {}), 7: ('wagtail.blocks.StreamBlock', [[('charts', 3), ('maps', 6)]], {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('content', 7)]], {})}),
        ),
    ]
