# Generated by Django 5.2.2 on 2025-10-28 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_languagesettings_default_language_and_more'),
        ('dashboards', '0008_alter_dashboardpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpage',
            name='service',
            field=models.OneToOneField(blank=True, help_text='The service this dashboard is associated with. This is useful in fetching the latest updates i.e publications, news, articles related to this service.', null=True, on_delete=django.db.models.deletion.PROTECT, to='base.servicecategory', verbose_name='Service'),
        ),
    ]
