# Generated by Django 5.2.1 on 2025-07-29 21:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_alter_dashboardpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 15)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section Title', 'max_length': 100, 'verbose_name': 'Section Title'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'code', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'hr', 'anchor', 'table', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull', 'indent', 'outdent', 'html'], 'help_text': 'Section description', 'verbose_name': 'Section Text'}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('text', 2)]], {'icon': 'document'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('text', 2), ('image', 4)]], {'icon': 'image'}), 6: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.ChartSnippet'}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('charts_block', 7)]], {}), 9: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.DashboardMap'}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('maps_block', 10)]], {}), 12: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': False, 'rowHeaders': False}}), 13: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 12)]], {'icon': 'table'}), 14: ('wagtail.blocks.StreamBlock', [[('title_text', 3), ('title_text_image', 5), ('chart', 8), ('map', 11), ('table', 13)]], {'required': True}), 15: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('content', 14)]], {})}),
        ),
    ]
