# Generated by Django 5.2.2 on 2026-02-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_dashboardpage_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsnippet',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line Chart'), ('column', 'Vertical Bar Chart'), ('bar', 'Horizontal Bar Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot'), ('warm_stripes', 'Warming stripes'), ('rain_stripes', 'Rainfall stripes')], default='line', max_length=255),
        ),
    ]
