# Generated by Django 5.2.1 on 2025-06-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_dashboardindexpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardIndexPage',
            new_name='DashboardGalleryPage',
        ),
        migrations.AlterModelOptions(
            name='dashboardgallerypage',
            options={'verbose_name': 'Dashboards Gallery'},
        ),
        migrations.AlterField(
            model_name='chartsnippet',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
