# Generated by Django 5.2.1 on 2025-07-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_alter_dashboardpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmap',
            name='boundary',
            field=models.TextField(blank=True, help_text='Boundary GeoJSON', null=True),
        ),
    ]
