# Generated by Django 5.2.2 on 2026-02-09 13:16

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_alter_chartsnippet_chart_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiVariableChartSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Description', null=True, verbose_name='Description')),
                ('variables', wagtail.fields.StreamField([('chart_variable', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Chart variable', 'required': True}), 1: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'table', 'target_model': 'geomanager.rasterfilelayer'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Data unit', 'required': False}), 3: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'default': '#0b76e1', 'label': 'Chart color', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('chart_variable', 0), ('dataset', 1), ('data_unit', 2), ('chart_color', 3)]], {})}, null=True, verbose_name='Chart Variables')),
            ],
        ),
        migrations.AlterModelOptions(
            name='chartsnippet',
            options={'verbose_name': 'Single-Variable Chart', 'verbose_name_plural': 'Single-Variable Charts'},
        ),
    ]
