# Generated by Django 5.2.2 on 2026-02-09 13:29

import django.contrib.gis.db.models.fields
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_multivariablechartsnippet_alter_chartsnippet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multivariablechartsnippet',
            options={'verbose_name': 'Multi-Variable Chart', 'verbose_name_plural': 'Multi-Variable Charts'},
        ),
        migrations.AddField(
            model_name='multivariablechartsnippet',
            name='admin_level',
            field=models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2')], default=0, help_text='Administrative Level', null=True),
        ),
        migrations.AddField(
            model_name='multivariablechartsnippet',
            name='area_desc',
            field=models.TextField(blank=True, help_text='Click on map to generate name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='multivariablechartsnippet',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='multivariablechartsnippet',
            name='geostore_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='multivariablechartsnippet',
            name='gid0',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='multivariablechartsnippet',
            name='gid1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='multivariablechartsnippet',
            name='gid2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='multivariablechartsnippet',
            name='variables',
            field=wagtail.fields.StreamField([('chart_variable', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Chart variable name', 'required': True}), 1: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'default': '#0b76e1', 'label': 'Chart color', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('line', 'Line Chart'), ('column', 'Vertical Bar Chart'), ('bar', 'Horizontal Bar Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot')], 'label': 'Chart type'}), 3: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'table', 'target_model': 'geomanager.rasterfilelayer'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Data unit', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('chart_variable', 0), ('chart_color', 1), ('chart_type', 2), ('dataset', 3), ('data_unit', 4)]], {})}, null=True, verbose_name='Chart Variables'),
        ),
    ]
