# Generated by Django 5.2.1 on 2025-07-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_remove_dashboardmap_boundary_chartsnippet_boundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartsnippet',
            name='boundary',
        ),
        migrations.AddField(
            model_name='dashboardmap',
            name='boundary',
            field=models.TextField(blank=True, help_text='Boundary GeoJSON', null=True),
        ),
    ]
