# Generated by Django 5.2.2 on 2026-02-10 10:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_alter_multivariablechartsnippet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivariablechartsnippet',
            name='multiple_axes',
            field=models.BooleanField(default=False, help_text='Whether to use multiple axes (one per variable) or a single axis for all variables.'),
        ),
        migrations.AlterField(
            model_name='dashboardpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 32)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section Title', 'max_length': 100, 'verbose_name': 'Section Title'}), 2: ('wagtail.blocks.StructBlock', [[('title', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'code', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'hr', 'anchor', 'table', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull', 'indent', 'outdent', 'html'], 'help_text': 'Section description', 'verbose_name': 'Section Text'}), 4: ('wagtail.blocks.StructBlock', [[('text', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('text', 3)]], {'icon': 'document'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 1), ('text', 3), ('image', 6)]], {'icon': 'image'}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.ChartSnippet'}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('charts_block', 9)]], {}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.MultiVariableChartSnippet'}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('multivariable_charts_block', 12)]], {}), 14: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.DashboardMap'}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('maps_block', 15)]], {}), 17: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': False, 'rowHeaders': False}}), 18: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 17)]], {'icon': 'table'}), 19: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'label': 'Icon', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4']}), 22: ('wagtail.blocks.StructBlock', [[('icon', 19), ('title', 20), ('description', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Card button text', 'max_length': 20, 'required': False}), 25: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Card button link', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('what_we_do_items', 23), ('what_we_do_button_text', 24), ('what_we_do_button_link', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {}), 28: ('wagtail.blocks.StructBlock', [[('heading', 27), ('description', 21), ('image', 6)]], {}), 29: ('wagtail.blocks.StreamBlock', [[('collapsibles', 28)]], {}), 30: ('wagtail.blocks.StructBlock', [[('title', 0), ('collapsibles', 29)]], {'icon': 'layer-group'}), 31: ('wagtail.blocks.StreamBlock', [[('title_only', 2), ('text_only', 4), ('title_text', 5), ('title_text_image', 7), ('chart', 10), ('multivariable_chart', 13), ('map', 16), ('table', 18), ('what_we_do', 26), ('accordion', 30)]], {'required': True}), 32: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('content', 31)]], {})}),
        ),
    ]
