# Generated by Django 5.2.2 on 2026-02-10 10:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_multivariablechartsnippet_multiple_axes_and_more'),
        ('geomanager', '0052_remove_rasterstyle_rendering_engine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChartSnippet',
            new_name='SingleVariableChartSnippet',
        ),
        migrations.AlterField(
            model_name='dashboardpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 32)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section Title', 'max_length': 100, 'verbose_name': 'Section Title'}), 2: ('wagtail.blocks.StructBlock', [[('title', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'code', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'hr', 'anchor', 'table', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull', 'indent', 'outdent', 'html'], 'help_text': 'Section description', 'verbose_name': 'Section Text'}), 4: ('wagtail.blocks.StructBlock', [[('text', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('text', 3)]], {'icon': 'document'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 1), ('text', 3), ('image', 6)]], {'icon': 'image'}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.SingleVariableChartSnippet'}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('singlevariable_charts_block', 9)]], {}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.MultiVariableChartSnippet'}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('multivariable_charts_block', 12)]], {}), 14: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'dashboards.DashboardMap'}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('maps_block', 15)]], {}), 17: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': False, 'rowHeaders': False}}), 18: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 17)]], {'icon': 'table'}), 19: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'label': 'Icon', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4']}), 22: ('wagtail.blocks.StructBlock', [[('icon', 19), ('title', 20), ('description', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Card button text', 'max_length': 20, 'required': False}), 25: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Card button link', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('what_we_do_items', 23), ('what_we_do_button_text', 24), ('what_we_do_button_link', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {}), 28: ('wagtail.blocks.StructBlock', [[('heading', 27), ('description', 21), ('image', 6)]], {}), 29: ('wagtail.blocks.StreamBlock', [[('collapsibles', 28)]], {}), 30: ('wagtail.blocks.StructBlock', [[('title', 0), ('collapsibles', 29)]], {'icon': 'layer-group'}), 31: ('wagtail.blocks.StreamBlock', [[('title_only', 2), ('text_only', 4), ('title_text', 5), ('title_text_image', 7), ('singlevariable_chart', 10), ('multivariable_chart', 13), ('map', 16), ('table', 18), ('what_we_do', 26), ('accordion', 30)]], {'required': True}), 32: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('content', 31)]], {})}),
        ),
        migrations.AlterField(
            model_name='multivariablechartsnippet',
            name='variables',
            field=wagtail.fields.StreamField([('chart_variable', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Chart variable name', 'required': True}), 1: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'default': '#0b76e1', 'label': 'Chart color', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('line', 'Line Chart'), ('column', 'Vertical Bar Chart'), ('bar', 'Horizontal Bar Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot')], 'label': 'Chart type'}), 3: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'table', 'target_model': 'geomanager.rasterfilelayer'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Data unit', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('chart_variable', 0), ('chart_color', 1), ('chart_type', 2), ('dataset', 3), ('data_unit', 4)]], {})}, help_text='Add more variables to display in the chart. Each variable corresponds to a dataset and will be displayed as a separate series in the chart.', null=True, verbose_name='Chart Variables'),
        ),
    ]
