# Generated by Django 5.2.1 on 2025-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_remove_chartsnippet_boundary_dashboardmap_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmap',
            name='boundary',
            field=models.CharField(blank=True, help_text='Boundary GeoJSON', null=True),
        ),
    ]
