# Generated by Django 5.2.1 on 2025-07-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0014_alter_dashboardmap_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmap',
            name='admin_level',
            field=models.CharField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1, help_text='Administrative Level', null=True),
        ),
        migrations.AddField(
            model_name='dashboardmap',
            name='areaDesc',
            field=models.TextField(help_text='The text describing the affected area of the alert message', max_length=50, null=True),
        ),
    ]
