# Generated by Django 5.2.2 on 2026-02-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0014_rename_chartsnippet_singlevariablechartsnippet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmap',
            name='mini_maps',
            field=models.BooleanField(default=False, help_text='Whether to show mini maps of each timestamp in the legend.'),
        ),
    ]
