# Generated by Django 5.2.1 on 2025-07-30 12:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_dashboardmap_admin_level_dashboardmap_areadesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmap',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
