# Generated by Django 5.2.2 on 2026-03-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_dashboardmap_mini_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardmap',
            name='mini_maps',
        ),
    ]
