# Generated by Django 5.2.1 on 2025-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0016_alter_dashboardmap_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmap',
            name='boundary',
            field=models.TextField(help_text='GeoJSON string of boundary', null=True),
        ),
    ]
