# Generated by Django 5.2.1 on 2025-07-31 10:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0019_alter_dashboardmap_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmap',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326, verbose_name='Area'),
        ),
    ]
