# Generated by Django 5.2.1 on 2025-07-31 15:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0020_alter_dashboardmap_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmap',
            name='admin_level',
            field=models.CharField(blank=True, choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1, help_text='Administrative Level', null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='areaDesc',
            field=models.TextField(blank=True, help_text='The text describing the affected area of the alert message', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Area'),
        ),
    ]
