# Generated by Django 5.2.1 on 2025-07-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0022_alter_dashboardmap_admin_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmap',
            name='admin_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=0, help_text='Administrative Level', null=True),
        ),
    ]
