# Generated by Django 5.2.1 on 2025-08-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0023_alter_dashboardmap_admin_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardmap',
            old_name='boundary',
            new_name='geom',
        ),
    ]
