# Generated by Django 5.2.1 on 2025-08-02 21:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0024_rename_boundary_dashboardmap_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartsnippet',
            name='admin_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=0, help_text='Administrative Level', null=True),
        ),
        migrations.AddField(
            model_name='chartsnippet',
            name='areaDesc',
            field=models.TextField(blank=True, help_text='The text describing the affected area of the alert message', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chartsnippet',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Area'),
        ),
    ]
