# Generated by Django 5.2.1 on 2025-08-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0025_chartsnippet_admin_level_chartsnippet_areadesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmap',
            name='admin_level',
            field=models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1, help_text='Administrative Level'),
        ),
    ]
