# Generated by Django 5.2.1 on 2025-08-03 11:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0027_alter_dashboardmap_map_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmap',
            name='map_layer',
            field=wagtail.fields.StreamField([('raster_file_layer', 1), ('wms_layer', 3), ('raster_tile_layer', 5), ('vector_tile_layer', 7)], block_lookup={0: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.rasterfilelayer'}), 1: ('wagtail.blocks.StructBlock', [[('layer', 0)]], {'icon': 'map', 'label': 'Raster Layer'}), 2: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.wmslayer'}), 3: ('wagtail.blocks.StructBlock', [[('layer', 2)]], {'icon': 'map', 'label': 'WMS Layer'}), 4: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.rastertilelayer'}), 5: ('wagtail.blocks.StructBlock', [[('layer', 4)]], {'icon': 'map', 'label': 'Raster XYZ Tile Layer'}), 6: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.vectortilelayer'}), 7: ('wagtail.blocks.StructBlock', [[('layer', 6)]], {'icon': 'map', 'label': 'Vector XYZ Tile Layer'})}, null=True, verbose_name='Map Layers'),
        ),
    ]
