# Generated by Django 5.2.1 on 2025-08-03 11:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0028_alter_dashboardmap_map_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmap',
            name='map_layer',
            field=wagtail.fields.StreamField([('raster_file_layer', 0), ('wms_layer', 1), ('raster_tile_layer', 2), ('vector_tile_layer', 3)], block_lookup={0: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.rasterfilelayer'}), 1: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.wmslayer'}), 2: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.rastertilelayer'}), 3: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.vectortilelayer'})}, null=True, verbose_name='Map Layers'),
        ),
    ]
