# Generated by Django 5.2.1 on 2025-08-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0029_alter_dashboardmap_map_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartsnippet',
            name='admin_path',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmap',
            name='admin_path',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
