# Generated by Django 5.2.1 on 2025-08-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0030_chartsnippet_admin_path_dashboardmap_admin_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartsnippet',
            old_name='areaDesc',
            new_name='area_desc',
        ),
        migrations.RenameField(
            model_name='dashboardmap',
            old_name='areaDesc',
            new_name='area_desc',
        ),
        migrations.AlterField(
            model_name='chartsnippet',
            name='admin_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2')], default=0, help_text='Administrative Level', null=True),
        ),
    ]
