# Generated by Django 5.2.1 on 2025-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0031_rename_areadesc_chartsnippet_area_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsnippet',
            name='admin_level',
            field=models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2')], default=0, help_text='Administrative Level', null=True),
        ),
        migrations.AlterField(
            model_name='chartsnippet',
            name='area_desc',
            field=models.TextField(help_text='The text describing the affected area of the alert message. Click on map to generate name', max_length=50, null=True),
        ),
    ]
