# Generated by Django 5.2.1 on 2025-08-07 10:43

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0032_alter_chartsnippet_admin_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsnippet',
            name='area_desc',
            field=models.TextField(blank=True, help_text='The text describing the affected area of the alert message. Click on map to generate name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chartsnippet',
            name='description',
            field=wagtail.fields.RichTextField(help_text='Description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='description',
            field=wagtail.fields.RichTextField(help_text='Description', verbose_name='Description'),
        ),
    ]
