# Generated by Django 5.2.1 on 2025-08-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0034_alter_chartsnippet_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsnippet',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line Chart'), ('column', 'Bar Chart'), ('boxplot', 'Box Plot'), ('scatter', 'Scatter Plot'), ('stripes', 'Warming stripes')], default='line', max_length=10),
        ),
    ]
