# Generated by Django 5.2.1 on 2025-08-19 10:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0035_alter_chartsnippet_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsnippet',
            name='description',
            field=wagtail.fields.RichTextField(help_text='Description', null=True, verbose_name='Description'),
        ),
    ]
