# Generated by Django 5.2.1 on 2025-08-19 10:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0037_alter_dashboardmap_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsnippet',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dashboardmap',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Description', null=True, verbose_name='Description'),
        ),
    ]
