# Generated by Django 5.2.1 on 2025-09-04 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0038_alter_chartsnippet_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='A high quality banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='chartsnippet',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line Chart'), ('column', 'Vertical Bar Chart'), ('bar', 'Horizontal Bar Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot'), ('stripes', 'Warming stripes')], default='line', max_length=10),
        ),
    ]
