# Generated by Django 4.1.7 on 2023-05-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webicons', '0004_alter_webicon_file'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackpage',
            name='illustration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webicons.webicon', verbose_name='Illustration'),
        ),
        migrations.AlterField(
            model_name='feedbackpage',
            name='introduction_subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction Subtitle'),
        ),
        migrations.AlterField(
            model_name='feedbackpage',
            name='introduction_title',
            field=models.TextField(verbose_name='Introduction Title'),
        ),
        migrations.AlterField(
            model_name='feedbackpage',
            name='thank_you_text',
            field=models.TextField(blank=True, null=True, verbose_name='Thank you Text'),
        ),
    ]
