# Generated by Django 4.1.9 on 2023-05-15 12:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('webicons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackpage',
            name='illustration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webicons.webicon', verbose_name='Illustration'),
        ),
        migrations.AddField(
            model_name='feedbackformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_form_fields', to='feedback.feedbackpage'),
        ),
    ]
