# Generated by Django 4.1.7 on 2023-04-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('mailchimper', '0002_mauticmailinglistsubscriptionpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingListSubscriptionPage',
            new_name='MailchimpMailingListSubscriptionPage',
        ),
    ]
