# Generated by Django 4.2.3 on 2023-09-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossaryitemdetailpage',
            name='term',
        ),
    ]
