# Generated by Django 4.2.3 on 2023-09-25 08:47

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_remove_glossaryitemdetailpage_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryitemdetailpage',
            name='simplified_definition',
            field=wagtail.fields.RichTextField(blank=True, help_text='Simplified definition of the term ', null=True, verbose_name='Simplified definition'),
        ),
    ]
