# Generated by Django 4.2.3 on 2023-09-25 08:59

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_alter_glossaryitemdetailpage_simplified_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossaryitemdetailpage',
            name='scientific_definition',
        ),
        migrations.RemoveField(
            model_name='glossaryitemdetailpage',
            name='simplified_definition',
        ),
        migrations.AddField(
            model_name='glossaryitemdetailpage',
            name='detail_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Detailed definition and description of the term. This should provide more information of the term, including images and other materials where available', null=True, verbose_name='Detailed description'),
        ),
        migrations.AddField(
            model_name='glossaryitemdetailpage',
            name='quick_definition',
            field=models.TextField(default='Quick', help_text='Summarized definition of the term', verbose_name='Quick definition'),
            preserve_default=False,
        ),
    ]
