# Generated by Django 4.2.3 on 2023-09-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0004_remove_glossaryitemdetailpage_scientific_definition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossaryitemdetailpage',
            name='quick_definition',
        ),
        migrations.AddField(
            model_name='glossaryitemdetailpage',
            name='brief_definition',
            field=models.TextField(default='Brief', help_text='Summarized definition of the term', verbose_name='Brief definition'),
            preserve_default=False,
        ),
    ]
