# Generated by Django 4.2.3 on 2023-09-25 09:44

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0005_remove_glossaryitemdetailpage_quick_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryitemdetailpage',
            name='local_definitions',
            field=wagtail.fields.StreamField([('definitions', wagtail.blocks.StructBlock([('language', wagtail.blocks.CharBlock(label='Product Type', required=True)), ('definition', wagtail.blocks.RichTextBlock(help_text='Definition of the term in the local language'))], label='Local Definition'))], blank=True, null=True, use_json_field=True, verbose_name='Local Definitions'),
        ),
        migrations.DeleteModel(
            name='GlossaryItemDefinition',
        ),
    ]
