# Generated by Django 3.2.20 on 2023-09-01 10:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectpage_feature_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='goals_block',
            field=wagtail.fields.StreamField([('goal', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4'])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True, use_json_field=True, verbose_name='Goals'),
        ),
    ]
