# Generated by Django 4.2.3 on 2024-03-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectindexpage_introduction_button_link_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='goals_title',
            field=models.CharField(blank=True, default='Our Areas of Work', max_length=200, null=True, verbose_name='Goals section title'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
    ]
