# Generated by Django 4.2.18 on 2025-03-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectpage_goals_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectindexpage',
            name='introduction_button_text',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Introduction button text'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='introduction_button_text',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Introduction button text'),
        ),
    ]
