# Generated by Django 4.2.2 on 2023-06-14 19:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(max_length=100, verbose_name='Title')),
                ('hero_subtitle', models.CharField(max_length=100, null=True, verbose_name='Subtitle')),
                ('hero_text_color', wagtail_color_panel.fields.ColorField(blank=True, default='#f0f0f0', max_length=7, null=True, verbose_name='Banner Text Color')),
                ('enable_weather_forecasts', models.BooleanField(default=True, verbose_name='Enable weather forecasts section')),
                ('enable_mapviewer_cta', models.BooleanField(default=True, verbose_name='Enable mapviewer section')),
                ('mapviewer_cta_title', models.CharField(blank=True, default='Explore MapViewer', max_length=100, null=True, verbose_name='MapViewer Call to Action Title')),
                ('mapviewer_cta_url', models.URLField(blank=True, null=True, verbose_name='Mapviewer URL')),
                ('enable_media', models.BooleanField(default=True, verbose_name='Enable media section')),
                ('video_section_title', models.CharField(blank=True, default='Latest Media', max_length=100, null=True, verbose_name='Media Section Title')),
                ('video_section_desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Media Section Description')),
                ('hero_banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
                ('youtube_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.youtubeplaylist', verbose_name='Youtube Playlist')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
    ]
