# Generated by Django 4.2.2 on 2023-06-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='enable_media',
            field=models.BooleanField(default=False, verbose_name='Enable media section'),
        ),
    ]
