# Generated by Django 4.2.2 on 2023-07-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_enable_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='enable_mapviewer_cta',
            field=models.BooleanField(default=False, verbose_name='Enable mapviewer section'),
        ),
    ]
