# Generated by Django 4.2.2 on 2023-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_enable_mapviewer_cta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='enable_mapviewer_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='enable_media',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='enable_weather_forecasts',
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_city_forecast',
            field=models.BooleanField(default=True, verbose_name='Show weather forecasts section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_mapviewer_cta',
            field=models.BooleanField(default=False, verbose_name='Show MapViewer button'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_media_section',
            field=models.BooleanField(default=False, verbose_name='Show media section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_weather_watch',
            field=models.BooleanField(default=True, verbose_name='Show weather watch section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='weather_watch_header',
            field=models.TextField(default='Our Weather Watch', max_length=100, verbose_name='Weather Watch Section header'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mapviewer_cta_title',
            field=models.CharField(blank=True, default='Explore on MapViewer', max_length=100, null=True, verbose_name='MapViewer Call to Action Title'),
        ),
    ]
