# Generated by Django 4.2.2 on 2023-08-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_show_city_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='weather_watch_header',
            field=models.CharField(default='Our Weather Watch', max_length=100, verbose_name='Weather Watch Section header'),
        ),
    ]
