# Generated by Django 4.2.3 on 2023-08-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_home_hero_type_alter_homepage_hero_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='home_hero_type',
            new_name='hero_type',
        ),
    ]
