# Generated by Django 4.2.3 on 2023-08-29 08:07

from django.db import migrations
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partnerspage_partners_cta_text_and_more'),
        ('home', '0010_alter_homepage_hero_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_block',
            field=wagtail.fields.StreamField([('feature_item', wagtail.blocks.StructBlock([('figure_type', wagtail.blocks.ChoiceBlock(choices=[('image', 'Image'), ('chart', 'Chart'), ('video', 'Video'), ('imageofchange', 'Image of Change')])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('chart_config_url', wagtail.blocks.URLBlock(help_text='A URL that returns Highcharts.js configuration, including the data', required=False)), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock(label='Description')), ('action_link_text', wagtail.blocks.CharBlock(max_length=15, required=False)), ('action_link', wagtail.blocks.PageChooserBlock(label='Action Link Internal', required=False)), ('action_link_external', wagtail.blocks.URLBlock(help_text='An external link to a detailed resource on the internet.If provided, the internal link will be ignored', max_length=400, required=False))]))], blank=True, null=True, use_json_field=True, verbose_name='Feature block'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='home', to='partners.partner', verbose_name='Partners'),
        ),
    ]
