# Generated by Django 4.2.3 on 2023-08-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_feature_block_homepage_partners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='partners',
        ),
    ]
