# Generated by Django 4.2.3 on 2023-11-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_feature_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='show_media_section',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='video_section_desc',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='video_section_title',
        ),
    ]
