# Generated by Django 4.2.3 on 2024-04-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homemapsettings_zoom_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pre_title',
            field=models.CharField(blank=True, help_text='Text to show before the name of the institution. For example, if the institution is under a ministry, the ministry name can added here', max_length=100, null=True, verbose_name='Pre Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Can be the tagline or slogan of the institution', max_length=100, null=True, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(help_text='Full name of the institution', max_length=100, verbose_name='Institution Name'),
        ),
    ]
