# Generated by Django 4.2.18 on 2025-04-23 07:50

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_homemapsettings_location_forecast_layer_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemapsettings',
            name='map_layers',
            field=wagtail.fields.StreamField([('raster_file_layer', 4), ('wms_layer', 6), ('vector_tile_layer', 8)], blank=True, block_lookup={0: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.rasterfilelayer'}), 1: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'default': 'layer-group', 'label': 'Icon', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name to display on the map. Leave blank to use the original layer name', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'You can only select one layer to be shown on the map by default. If multiple layers are selected, only the first one will be shown', 'label': 'Show on map by default ?', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('layer', 0), ('icon', 1), ('display_name', 2), ('default', 3)]], {'icon': 'map', 'label': 'Raster Layer'}), 5: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.wmslayer'}), 6: ('wagtail.blocks.StructBlock', [[('layer', 5), ('icon', 1), ('display_name', 2), ('default', 3)]], {'icon': 'map', 'label': 'WMS Layer'}), 7: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.vectortilelayer'}), 8: ('wagtail.blocks.StructBlock', [[('layer', 7), ('icon', 1), ('display_name', 2), ('default', 3)]], {'icon': 'map', 'label': 'Vector Tile Layer'})}, null=True, verbose_name='Map Layers'),
        ),
    ]
