# Generated by Django 4.2.18 on 2025-04-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_homemapsettings_zoom_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemapsettings',
            name='show_forecast_attribution',
            field=models.BooleanField(default=True, verbose_name='Show Location Forecast Attribution'),
        ),
    ]
