# Generated by Django 4.2.18 on 2025-05-21 08:18

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_homemapsettings_map_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemapsettings',
            name='map_layers',
            field=wagtail.fields.StreamField([('raster_file_layer', 5), ('wms_layer', 7), ('vector_tile_layer', 9)], blank=True, block_lookup={0: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.rasterfilelayer'}), 1: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'default': 'layer-group', 'label': 'Icon', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name to display on the map. Leave blank to use the original layer name', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Enabled', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'You can only select one layer to be shown on the map by default. If multiple layers are selected, only the first one will be shown', 'label': 'Show on map by default ?', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('layer', 0), ('icon', 1), ('display_name', 2), ('enabled', 3), ('default', 4)]], {'icon': 'map', 'label': 'Raster Layer'}), 6: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.wmslayer'}), 7: ('wagtail.blocks.StructBlock', [[('layer', 6), ('icon', 1), ('display_name', 2), ('enabled', 3), ('default', 4)]], {'icon': 'map', 'label': 'WMS Layer'}), 8: ('climweb.base.blocks.UUIDModelChooserBlock', (), {'icon': 'map', 'target_model': 'geomanager.vectortilelayer'}), 9: ('wagtail.blocks.StructBlock', [[('layer', 8), ('icon', 1), ('display_name', 2), ('enabled', 3), ('default', 4)]], {'icon': 'map', 'label': 'Vector Tile Layer'})}, null=True, verbose_name='Map Layers'),
        ),
        migrations.AlterField(
            model_name='homemapsettings',
            name='show_forecast_attribution',
            field=models.BooleanField(default=False, verbose_name='Show Location Forecast Attribution'),
        ),
    ]
