# Generated by Django 4.2.18 on 2025-05-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_homemapsettings_map_layers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemapsettings',
            name='show_level_1_boundaries',
            field=models.BooleanField(default=False, verbose_name='Show Level 1 Boundaries'),
        ),
        migrations.AddField(
            model_name='homemapsettings',
            name='use_geomanager_basemaps',
            field=models.BooleanField(default=False, verbose_name='Use Geomanager Basemaps, if set'),
        ),
    ]
