# Generated by Django 5.2.2 on 2025-11-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_homemapsettings_show_level_1_boundaries_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_youtube_video_id',
            field=models.CharField(blank=True, help_text="YouTube Video ID (e.g., 'dQw4w9WgXcQ' from https://www.youtube.com/watch?v=dQw4w9WgXcQ). Only used if 'Use YouTube Video as Banner' is enabled.", max_length=100, null=True, verbose_name='YouTube Video ID'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_banner_video',
            field=models.BooleanField(default=False, help_text='If enabled, the YouTube video will be used as the banner background instead of the banner image', verbose_name='Use YouTube Video as Banner'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image'),
        ),
    ]
