# Generated by Django 5.2.2 on 2026-03-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_homepage_banner_youtube_video_id_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='call_to_action_button_text_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='call_to_action_button_text_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='call_to_action_related_page_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='call_to_action_related_page_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page 3'),
        ),
    ]
