# Generated by Django 5.2.12 on 2026-04-16 14:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_homepage_call_to_action_button_text_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemapsettings',
            name='zoom_locations',
            field=wagtail.fields.StreamField([('boundary_block', 2), ('polygon_block', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Area/Region Name'}), 1: ('wagtail.blocks.BooleanBlock', (), {'label': 'Default', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('areaDesc', 0), ('default', 1)]], {'label': 'Admin Boundary'}), 3: ('wagtail.blocks.StructBlock', [[('areaDesc', 0), ('default', 1)]], {'label': 'Draw Polygon'})}),
        ),
    ]
