# Generated by Django 5.2.2 on 2026-04-17 08:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_homemapsettings_zoom_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='stats_bar',
            field=wagtail.fields.StreamField([('stat', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 47, 2.4M, 138', 'label': 'Value', 'max_length': 20}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Regional Centers', 'label': 'Label', 'max_length': 100}), 2: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1)]], {'label': 'Stat Item'})}, help_text='Displayed below the hero on non-meteorological sites. Add up to 4 items.', null=True, verbose_name='Stats Bar'),
        ),
    ]
