# Generated by Django 5.2.2 on 2026-04-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_homepage_stats_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Can be the tagline or slogan of the institution', max_length=200, null=True, verbose_name='Tagline'),
        ),
    ]
