# Generated by Django 5.2.12 on 2026-04-17 11:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_homepage_hero_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemapsettings',
            name='zoom_locations',
            field=wagtail.fields.StreamField([('boundary_block', 4), ('polygon_block', 6)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Area/Region Name'}), 1: ('wagtail.blocks.BooleanBlock', (), {'label': 'Default', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], 'label': 'Administrative Level'}), 3: ('capcomposer.capeditor.blocks.BoundaryFieldBlock', (), {'help_text': 'Click to select boundary on the map', 'label': 'Boundary'}), 4: ('wagtail.blocks.StructBlock', [[('areaDesc', 0), ('default', 1), ('admin_level', 2), ('boundary', 3)]], {'label': 'Admin Boundary'}), 5: ('capcomposer.capeditor.blocks.PolygonOrMultiPolygonFieldBlock', (), {'help_text': 'Draw custom area on the map', 'label': 'Polygon'}), 6: ('wagtail.blocks.StructBlock', [[('areaDesc', 0), ('default', 1), ('polygon', 5)]], {'label': 'Draw Polygon'})}),
        ),
    ]
