# Generated by Django 5.2.12 on 2026-05-11 04:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_homemapsettings_zoom_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemapsettings',
            name='zoom_locations',
            field=wagtail.fields.StreamField([('boundary_block', 2), ('polygon_block', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Area/Region Name'}), 1: ('wagtail.blocks.BooleanBlock', (), {'label': 'Default', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('areaDesc', 0), ('default', 1)]], {'label': 'Admin Boundary'}), 3: ('wagtail.blocks.StructBlock', [[('areaDesc', 0), ('default', 1)]], {'label': 'Draw Polygon'})}),
        ),
    ]
