# Generated by Django 5.2.12 on 2026-05-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_homemapsettings_zoom_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_youtube_video_id',
            field=models.CharField(blank=True, help_text="YouTube Video ID. Only used if 'Use YouTube Video as Banner' is enabled.", max_length=100, null=True, verbose_name='YouTube Video ID'),
        ),
    ]
