# Generated by Django 4.2.2 on 2023-06-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('playlist_id', models.CharField(help_text='This is the playlist ID as obtained from Youtube. If the playlist is not created on Youtube, please create it first', max_length=100, verbose_name='Playlist ID')),
            ],
        ),
    ]
