# Generated by Django 4.2.2 on 2023-06-15 10:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='footer_menu',
            field=wagtail.fields.StreamField([('navigation_item', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=False)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False)), ('include_subpages', wagtail.blocks.BooleanBlock(label='Include Subpages', required=False)), ('large_submenu', wagtail.blocks.BooleanBlock(label='Large Submenu Dropdown', required=False)), ('sub_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=False)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='feedback_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Feedback page'),
        ),
    ]
