# Generated by Django 4.2.2 on 2023-06-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_navigationsettings_footer_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsetting',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation Name'),
        ),
    ]
