# Generated by Django 4.2.2 on 2023-06-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationsettings',
            name='enable_auto_forecast',
        ),
        migrations.DeleteModel(
            name='MeasurementSettings',
        ),
    ]
