# Generated by Django 4.2.2 on 2023-06-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_integrationsettings_enable_auto_forecast_and_more'),
        ('base', '0011_alter_navigationsettings_footer_menu_and_more'),
    ]

    operations = [
    ]
