# Generated by Django 4.1.9 on 2023-07-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('base', '0012_merge_20230618_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsetting',
            name='country_flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Country Flag'),
        ),
    ]
