# Generated by Django 4.1.9 on 2023-07-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_organisationsetting_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherSettings',
        ),
    ]
