# Generated by Django 4.1.9 on 2023-07-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_delete_othersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationsettings',
            name='recaptcha_private_key',
        ),
        migrations.RemoveField(
            model_name='integrationsettings',
            name='recaptcha_public_key',
        ),
    ]
