# Generated by Django 4.1.9 on 2023-07-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_integrationsettings_recaptcha_private_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importantpages',
            options={'verbose_name': 'Important Pages', 'verbose_name_plural': 'Important Pages'},
        ),
        migrations.AlterModelOptions(
            name='navigationsettings',
            options={'verbose_name': 'Navigation Setting', 'verbose_name_plural': 'Navigation Settings'},
        ),
    ]
