# Generated by Django 4.2.3 on 2023-09-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20230918_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_view_geomanager_menu', 'Can view Geomanager menu'), ('can_view_survey_menu', 'Can View Survey menu'), ('can_view_alerts_menu', 'Can view CAP Alerts Menu'), ('can_view_forecast_menu', 'Can view Forecast Menu')),
                'default_permissions': [],
            },
        ),
    ]
