# Generated by Django 4.2.3 on 2023-10-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_create_menu_access_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationsetting',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=255, null=True, verbose_name='Phone number'),
        ),
    ]
