# Generated by Django 4.2.3 on 2024-01-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('base', '0025_alter_organisationsetting_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importantpages',
            name='cap_feed',
        ),
        migrations.AddField(
            model_name='importantpages',
            name='cap_warnings_list_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='CAP Warnings List page'),
        ),
    ]
