# Generated by Django 4.2.7 on 2024-06-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_servicecategory_options_servicecategory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
