# Generated by Django 4.2.18 on 2025-04-03 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0051_rasterstyle_rendering_engine'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('base', '0031_alter_menupermission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPGeomanagerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_mapviewer', models.BooleanField(default=True, help_text='Check to show cap alerts on MapViewer', verbose_name='Show on MapViewer')),
                ('layer_title', models.CharField(blank=True, default='Weather Alerts', max_length=100, null=True, verbose_name='CAP Alerts Layer Title')),
                ('auto_refresh_interval', models.IntegerField(blank=True, help_text='Refresh cap alerts on the map after this minutes. Leave blank to disable auto refreshing', null=True, verbose_name='Auto Refresh interval in minutes')),
                ('geomanager_layer_metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomanager.metadata', verbose_name='CAP Layer Metadata')),
                ('geomanager_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomanager.subcategory', verbose_name='CAP Alerts Layer SubCategory')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
