# Generated by Django 4.2.18 on 2025-04-16 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('base', '0032_capgeomanagersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocumentmodel',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
