# Generated by Django 5.2.2 on 2025-11-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_languagesettings_default_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='track_internally',
            field=models.BooleanField(default=True, help_text='Track   all pages internally. This will enable the internal analytics dashboard, alongside Google Analytics, if also enabled', verbose_name='Track pages internally'),
        ),
    ]
