# Generated by Django 5.2.1 on 2025-07-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_languagesettings_default_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesettings',
            name='default_language',
            field=models.CharField(blank=True, choices=[('af', 'Afrikaans'), ('sq', 'Albanian'), ('am', 'Amharic'), ('ar', 'Arabic'), ('hy', 'Armenian'), ('as', 'Assamese'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('bm', 'Bambara'), ('eu', 'Basque'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('bho', 'Bhojpuri'), ('bs', 'Bosnian'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('ceb', 'Cebuano'), ('ny', 'Chichewa'), ('zh-CN', 'Chinese'), ('co', 'Corsican'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('dv', 'Dhivehi'), ('doi', 'Dogri'), ('nl', 'Dutch'), ('en', 'English'), ('eo', 'Esperanto'), ('et', 'Estonian'), ('ee', 'Ewe'), ('tl', 'Filipino'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('gl', 'Galician'), ('ka', 'Georgian'), ('de', 'German'), ('el', 'Greek'), ('gn', 'Guarani'), ('gu', 'Gujarati'), ('ht', 'Haitian Creole'), ('ha', 'Hausa'), ('haw', 'Hawaiian'), ('iw', 'Hebrew'), ('hi', 'Hindi'), ('hmn', 'Hmong'), ('hu', 'Hungarian'), ('is', 'Icelandic'), ('ig', 'Igbo'), ('ilo', 'Ilocano'), ('id', 'Indonesian'), ('ga', 'Irish'), ('it', 'Italian'), ('ja', 'Japanese'), ('jw', 'Javanese'), ('kn', 'Kannada'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('rw', 'Kinyarwanda'), ('gom', 'Konkani'), ('ko', 'Korean'), ('kri', 'Krio'), ('ku', 'Kurdish (Kurmanji)'), ('ckb', 'Kurdish (Sorani)'), ('ky', 'Kyrgyz'), ('lo', 'Lao'), ('la', 'Latin'), ('lv', 'Latvian'), ('ln', 'Lingala'), ('lt', 'Lithuanian'), ('lg', 'Luganda'), ('lb', 'Luxembourgish'), ('mk', 'Macedonian'), ('mai', 'Maithili'), ('mg', 'Malagasy'), ('ms', 'Malay'), ('ml', 'Malayalam'), ('mt', 'Maltese'), ('mi', 'Maori'), ('mr', 'Marathi'), ('mni-Mtei', 'Meiteilon (Manipuri)'), ('lus', 'Mizo'), ('mn', 'Mongolian'), ('my', 'Myanmar (Burmese)'), ('ne', 'Nepali'), ('no', 'Norwegian'), ('or', 'Odia (Oriya)'), ('om', 'Oromo'), ('ps', 'Pashto'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pa', 'Punjabi'), ('qu', 'Quechua'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sm', 'Samoan'), ('sa', 'Sanskrit'), ('gd', 'Scots Gaelic'), ('nso', 'Sepedi'), ('sr', 'Serbian'), ('st', 'Sesotho'), ('crs', 'Seychellois Creole'), ('sn', 'Shona'), ('sd', 'Sindhi'), ('si', 'Sinhala'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('so', 'Somali'), ('es', 'Spanish'), ('su', 'Sundanese'), ('sw', 'Swahili'), ('sv', 'Swedish'), ('tg', 'Tajik'), ('ta', 'Tamil'), ('tt', 'Tatar'), ('te', 'Telugu'), ('th', 'Thai'), ('ti', 'Tigrinya'), ('ts', 'Tsonga'), ('tr', 'Turkish'), ('tk', 'Turkmen'), ('ak', 'Twi'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('ug', 'Uyghur'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('cy', 'Welsh'), ('xh', 'Xhosa'), ('yi', 'Yiddish'), ('yo', 'Yoruba'), ('zu', 'Zulu')], default='ar', max_length=10, null=True, verbose_name='Default Language'),
        ),
    ]
