# Generated by Django 5.2.2 on 2026-04-20 11:23

import wagtail_color_panel.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_organisationsetting_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='primary_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#363636', help_text='Primary color (use color picker)', max_length=7, null=True, verbose_name='Headings color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary_hover_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#176c9c', help_text='Primary Hover color (use color picker)', max_length=7, null=True, verbose_name='Primary color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#ffffff', help_text='Secondary color (use color picker)', max_length=7, null=True, verbose_name='Background color'),
        ),
    ]
