# Generated by Django 5.2.12 on 2026-05-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_theme_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermission',
            options={'default_permissions': [], 'permissions': (('can_view_geomanager_menu', 'Can view Geomanager menu'), ('can_view_survey_menu', 'Can View Survey menu'), ('can_view_alerts_menu', 'Can view CAP Alerts Menu'), ('can_view_forecast_menu', 'Can view Forecast Menu'))},
        ),
    ]
