# Generated by Django 5.2.12 on 2026-05-11 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_menupermission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='border_radius',
            field=models.IntegerField(default=12, help_text='Minimum 0 and Maximum 20 pixels', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Border radius (px)'),
        ),
    ]
