# Generated by Django 5.2.12 on 2026-05-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_product_ingestion_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variable_name',
            field=models.SlugField(blank=True, help_text="Folder name for this product, e.g. 'daily_forecast'. Used as the top-level folder in the watch root path.", max_length=100, verbose_name='Variable Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='watch_root',
            field=models.CharField(blank=True, help_text="Path containing the {variable_name} folder. Relative paths are resolved from MEDIA_ROOT (e.g. 'products'). Full scan path: {watch_root}/{variable_name}/{format}/{name_convention}.{format}", max_length=500, verbose_name='Watch Root Path'),
        ),
    ]
