# Generated by Django 5.2.12 on 2026-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_product_variable_name_alter_product_watch_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitemtype',
            name='valid_for_days',
            field=models.PositiveIntegerField(blank=True, help_text='How many days this product remains effective after its issue date. Leave blank if not applicable. E.g. 1 for daily, 7 for weekly, 30 for monthly.', null=True, verbose_name='Valid for (days)'),
        ),
    ]
