# Generated by Django 5.2.14 on 2026-07-13 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_productitemtype_valid_for_days'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantpages',
            name='anticipatory_action_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Anticipatory Action page'),
        ),
    ]
