# Generated by Django 5.2.14 on 2026-07-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_importantpages_anticipatory_action_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsetting',
            name='logo_append',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logo Append Text'),
        ),
    ]
