# Generated by Django 5.2.14 on 2026-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_backupsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
