# Generated by Django 5.2.14 on 2026-07-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_alter_backupsettings_id'),
        ('base', '0046_backupsettings_oauth_fields'),
    ]

    operations = [
    ]
