# Generated by Django 5.2.14 on 2026-07-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_backupsettings_sftp'),
        ('base', '0049_alter_aisettings_model_id_help'),
    ]

    operations = [
    ]
