# Generated by Django 5.2.14 on 2026-07-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_backupsettings_notify_email'),
        ('base', '0050_merge_20260721_1858'),
    ]

    operations = [
    ]
