# Generated by Django 5.2.14 on 2026-07-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_merge_20260721_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='backupsettings',
            name='provider',
            field=models.CharField(choices=[('gdrive', 'Google Drive'), ('sftp', 'Remote server (SFTP)')], default='gdrive', max_length=20, verbose_name='Provider'),
        ),
    ]
