# Generated by Django 5.2.14 on 2026-08-07 08:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_navigationsettings_footer_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='footer_menu',
            field=wagtail.fields.StreamField([('navigation_item', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Label'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Open in new tab. (Applies only to external URLs)', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'label': 'Include Subpages', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'label': 'Large Submenu Dropdown', 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'label': 'Show as action button', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('external_url', 2), ('open_in_new_tab', 3), ('is_action', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('sub_item', 7)]], {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('external_url', 2), ('open_in_new_tab', 3), ('include_subpages', 4), ('large_submenu', 5), ('sub_items', 8)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='main_menu',
            field=wagtail.fields.StreamField([('navigation_item', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Label'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Open in new tab. (Applies only to external URLs)', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'label': 'Include Subpages', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'label': 'Large Submenu Dropdown', 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'label': 'Show as action button', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('external_url', 2), ('open_in_new_tab', 3), ('is_action', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('sub_item', 7)]], {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('external_url', 2), ('open_in_new_tab', 3), ('include_subpages', 4), ('large_submenu', 5), ('sub_items', 8)]], {})}, null=True),
        ),
    ]
