# Generated by Django 5.2.16 on 2026-08-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_product_auto_description_from_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='youtube_api',
            field=models.CharField(blank=True, help_text='لإعداد مفتاح Youtube API، راجعhttps://developers.google.com/youtube/v3/getting-started', max_length=50, verbose_name='Youtube API Key'),
        ),
    ]
