# Generated by Django 5.2.16 on 2026-09-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alter_integrationsettings_youtube_api'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['order'], 'verbose_name': 'GIS Application', 'verbose_name_plural': 'GIS Applications'},
        ),
    ]
