# Generated by Django 5.2.16 on 2026-09-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_application_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['order'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterField(
            model_name='integrationsettings',
            name='youtube_api',
            field=models.CharField(blank=True, help_text='To set up Youtube API Key refer to https://developers.google.com/youtube/v3/getting-started', max_length=50, verbose_name='Youtube API Key'),
        ),
    ]
