# Generated by Django 4.2.18 on 2025-01-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackpage',
            name='introduction_title',
            field=models.CharField(verbose_name='Introduction Title'),
        ),
    ]
