# Generated by Django 4.2.3 on 2023-08-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpage_mission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='call_to_action_button_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='call_to_action_related_page',
        ),
    ]
