# Generated by Django 3.2.20 on 2023-09-01 10:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_aboutpage_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='accordion',
            field=wagtail.fields.StreamField([('accordion', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('collapsibles', wagtail.blocks.StreamBlock([('collapsibles', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'ul', 'ol', 'link', 'superscript', 'subscript'])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))]))]))], blank=True, null=True, use_json_field=True, verbose_name='Accordion'),
        ),
    ]
