# Generated by Django 4.1.9 on 2023-05-15 12:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('text_color', wagtail_color_panel.fields.ColorField(blank=True, default='#f0f0f0', max_length=7, null=True, verbose_name='Text Color')),
                ('hero_title', models.CharField(default='National Meteorological & Hydrological Services', max_length=100, null=True, verbose_name='Title')),
                ('hero_subtitle', models.CharField(default='Observing and understanding weather and climate', max_length=100, null=True, verbose_name='Subtitle Title')),
                ('enable_weather_forecasts', models.BooleanField(blank=True, default=True, verbose_name='Enable weather forecasts section')),
                ('enable_climate', models.BooleanField(blank=True, default=True, verbose_name='Enable climate section')),
                ('climate_title', models.CharField(blank=True, default='Explore Current Conditions', max_length=100, null=True, verbose_name='Climate Title')),
                ('enable_media', models.BooleanField(blank=True, default=True, verbose_name='Enable media section')),
                ('video_section_title', models.CharField(default='Latest Media', max_length=100, null=True, verbose_name='Media Section Title')),
                ('video_section_desc', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan, metus ultriceseleifend gt', max_length=500, null=True, verbose_name='Media Section Description')),
                ('hero_banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero Banner')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
