# Generated by Django 4.1.5 on 2023-02-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_city_forecast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
