# Generated by Django 4.1.5 on 2023-02-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_options_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(max_length=100, null=True, verbose_name='Subtitle Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
