# Generated by Django 4.1.5 on 2023-02-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='climate_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Climate Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='enable_climate',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
