# Generated by Django 4.1.5 on 2023-02-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_enable_weather_forecasts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='Observing and understanding weather and climate', max_length=100, null=True, verbose_name='Subtitle Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='National Meteorological & Hydrological Services', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
