# Generated by Django 4.1.5 on 2023-02-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0009_alter_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
