# Generated by Django 4.1.5 on 2023-02-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_hero_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='National Meteorological & Hydrological Services', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
