# Generated by Django 4.1.5 on 2023-02-21 04:30

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='text_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#f0f0f0', max_length=7, null=True),
        ),
    ]
