# Generated by Django 4.1.7 on 2023-02-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
