# Generated by Django 4.1.7 on 2023-03-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_homepage_video_section_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='video_section_desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan, metus ultriceseleifend gt', max_length=500, null=True, verbose_name='Media Section Description'),
        ),
    ]
