# Generated by Django 4.1.7 on 2023-03-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_homepage_video_section_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='enable_media',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
