# Generated by Django 4.1.7 on 2023-05-02 14:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('videos', '0002_alter_videogallerypage_introduction_and_more'),
        ('home', '0022_alter_homepage_youtube_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='enable_climate',
            field=models.BooleanField(blank=True, default=True, verbose_name='Enable climate section'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='enable_media',
            field=models.BooleanField(blank=True, default=True, verbose_name='Enable media section'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='enable_weather_forecasts',
            field=models.BooleanField(blank=True, default=True, verbose_name='Enable weather forecasts section'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero Banner'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#f0f0f0', max_length=7, null=True, verbose_name='Text Color'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='youtube_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.youtubeplaylist', verbose_name='Youtube Playlist'),
        ),
    ]
