# Generated by Django 4.1.7 on 2023-05-02 14:25

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogallerypage',
            name='introduction',
            field=wagtail.fields.RichTextField(verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='playlist_id',
            field=models.CharField(help_text='This is the playlist ID as obtained from Youtube. If the playlist is not created on Youtube, please create it first', max_length=100, verbose_name='Playlist ID'),
        ),
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
