# Generated by Django 4.1.7 on 2023-05-02 14:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('videos', '0002_alter_videogallerypage_introduction_and_more'),
        ('mediacenter', '0002_alter_mediaindexpage_banner_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaindexpage',
            options={'verbose_name': 'Media Page'},
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner Subtitle'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='banner_title',
            field=models.CharField(max_length=255, verbose_name='Banner Title'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='call_to_action_button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='call_to_action_external_link',
            field=models.URLField(blank=True, help_text='External Link if applicable', null=True, verbose_name='Call to action external link'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='call_to_action_related_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='introduction_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Introduction button link'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='introduction_button_link_external',
            field=models.URLField(blank=True, help_text='External Link if applicable. Ignored if internal page above is chosen', null=True, verbose_name='Introduction button link external'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='introduction_button_text',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Introduction button text'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='introduction_text',
            field=wagtail.fields.RichTextField(verbose_name='Introduction text'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='introduction_title',
            field=models.CharField(help_text='Introduction section title', max_length=100, verbose_name='Introduction title'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='youtube_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.youtubeplaylist', verbose_name='Youtube playlist'),
        ),
    ]
