# Generated by Django 4.1.9 on 2023-06-12 11:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('mediacenter', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaindexpage',
            name='call_to_action_external_link',
        ),
        migrations.RemoveField(
            model_name='mediaindexpage',
            name='introduction_button_link_external',
        ),
        migrations.AddField(
            model_name='mediaindexpage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='A high quality banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='introduction_image',
            field=models.ForeignKey(blank=True, help_text='A high quality image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Introduction Image'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='introduction_text',
            field=wagtail.fields.RichTextField(help_text='Introduction section description', verbose_name='Introduction text'),
        ),
        migrations.AlterField(
            model_name='mediaindexpage',
            name='introduction_title',
            field=models.CharField(help_text='Introduction section title', max_length=100, verbose_name='Call to action related page'),
        ),
    ]
