# Generated by Django 4.2.2 on 2023-08-08 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0003_capalertpage_search_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capalertpage',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID. Auto generated on creation.', unique=True, verbose_name='Identifier'),
        ),
    ]
