# Generated by Django 4.2.2 on 2023-08-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0005_capalertlistpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capalertlistpage',
            name='description',
        ),
        migrations.AddField(
            model_name='capalertlistpage',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CAP Alerts Heading'),
        ),
    ]
