# Generated by Django 4.2.3 on 2023-11-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0008_alter_capalertpage_info'),
        ('cap', '0008_capgeomanagersettings'),
    ]

    operations = [
    ]
