# Generated by Django 4.2.3 on 2024-04-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('cap', '0013_capalertpage_alert_pdf_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='capalertpage',
            name='alert_area_map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
