# Generated by Django 4.2.7 on 2024-05-30 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cap', '0015_alter_capalertpage_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capalertpage',
            old_name='identifier',
            new_name='guid'
        ),

    ]
