# Generated by Django 4.1.7 on 2023-03-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmsrequest',
            options={'verbose_name': 'WMS Request', 'verbose_name_plural': 'WMS Requests'},
        ),
    ]
