# Generated by Django 4.1.9 on 2023-05-15 12:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webicons', '0001_initial'),
        ('layer_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsrequest',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webicons.webicon'),
        ),
        migrations.AddField(
            model_name='wmsrequest',
            name='legend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='layer_manager.legend'),
        ),
        migrations.AddField(
            model_name='param',
            name='wms_request',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='layer_manager.wmsrequest', verbose_name='Addtional Parameters'),
        ),
        migrations.AddField(
            model_name='legenditem',
            name='legend',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legend_items', to='layer_manager.legend', verbose_name='Legend Items'),
        ),
        migrations.AddField(
            model_name='layer',
            name='wms_request',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='layer_manager.wmsrequest', verbose_name='WMS Layers'),
        ),
    ]
