# Generated by Django 4.1.7 on 2023-03-07 14:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('layer_manager', '0002_alter_wmsrequest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legend',
            name='wms_request',
        ),
        migrations.AddField(
            model_name='wmsrequest',
            name='legend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='layer_manager.legend'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='wms_request',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='layer_manager.wmsrequest', verbose_name='WMS Layers'),
        ),
        migrations.AlterField(
            model_name='legenditem',
            name='item_val',
            field=models.CharField(help_text="Can be a number or text e.g '10' or '10-20' or 'Vegetation'", max_length=50, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='legenditem',
            name='legend',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legend_items', to='layer_manager.legend', verbose_name='Legend Items'),
        ),
        migrations.AlterField(
            model_name='param',
            name='wms_request',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='layer_manager.wmsrequest', verbose_name='Addtional Parameters'),
        ),
        migrations.AlterField(
            model_name='wmsstyle',
            name='wms_request',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='layer_manager.wmsrequest', verbose_name='WMS Styles'),
        ),
    ]
