# Generated by Django 4.1.7 on 2023-03-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer_manager', '0003_remove_legend_wms_request_wmsrequest_legend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsrequest',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle of your layer', max_length=250, null=True, verbose_name='Layer Title'),
        ),
    ]
