# Generated by Django 4.1.7 on 2023-03-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer_manager', '0004_wmsrequest_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmsrequest',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle of your layer', max_length=250, null=True, verbose_name='Layer Subtitle'),
        ),
    ]
