# Generated by Django 4.1.7 on 2023-03-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layer_manager', '0005_alter_wmsrequest_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='WMS Layer Category name', max_length=250)),
                ('description', models.CharField(blank=True, help_text='WMS Layer Category description', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wmsrequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='layer_manager.layercategory'),
        ),
    ]
