# Generated by Django 4.1.7 on 2023-03-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer_manager', '0005_alter_wmsrequest_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='WMS Layer Category name', max_length=250)),
                ('description', models.CharField(help_text='WMS Layer Category description', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Layer Categories',
            },
        ),
        migrations.AddField(
            model_name='wmsrequest',
            name='base_url',
            field=models.CharField(default='http://20.56.94.119/gsky/ows/gfs', help_text='BASE URL for WMS', max_length=250, verbose_name='BASE URL for WMS'),
        ),
    ]
