# Generated by Django 4.1.7 on 2023-03-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layer_manager', '0007_alter_wmsrequest_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layercategory',
            options={'verbose_name_plural': 'Layer Categories'},
        ),
        migrations.AddField(
            model_name='wmsrequest',
            name='base_url',
            field=models.CharField(default='http://20.56.94.119/gsky/ows/gfs', help_text='BASE URL for WMS', max_length=250, verbose_name='BASE URL for WMS'),
        ),
        migrations.AlterField(
            model_name='wmsrequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='layer_manager.layercategory', verbose_name='Layer Categories'),
        ),
    ]
