# Generated by Django 4.2.3 on 2023-09-27 11:16

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtailcache.cache
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction_title', models.CharField(help_text='Introduction section title', max_length=100, verbose_name='Introduction Title')),
                ('introduction_text', wagtail.fields.RichTextField(help_text='Introduction section description', verbose_name='Introduction text')),
                ('introduction_button_text', models.TextField(blank=True, max_length=20, null=True, verbose_name='Introduction button text')),
                ('introduction_button_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Introduction button link')),
                ('introduction_image', models.ForeignKey(blank=True, help_text='A high quality image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Introduction Image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
        migrations.CreateModel(
            name='GlossaryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Language name')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='glossary.glossaryindexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlossaryItemDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('brief_definition', models.TextField(help_text='Summarized definition of the term', verbose_name='Brief definition')),
                ('detail_description', wagtail.fields.RichTextField(blank=True, help_text='Detailed definition and description of the term. This should provide more information of the term, including images and other materials where available', null=True, verbose_name='Detailed description')),
                ('local_definitions', wagtail.fields.StreamField([('definitions', wagtail.blocks.StructBlock([('language', wagtail.blocks.CharBlock(label='Language', required=True)), ('definition', wagtail.blocks.RichTextBlock(help_text='Definition of the term in the local language')), ('contributors', wagtail.blocks.StreamBlock([('contributor', wagtail.blocks.ChoiceBlock(choices=[], label='Contributor'))], required=False))], label='Local Definition'))], blank=True, null=True, use_json_field=True, verbose_name='Local Definitions')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
        migrations.CreateModel(
            name='GlossaryContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Name of Contributor', max_length=100, verbose_name='Contributor name')),
                ('organisation', models.CharField(blank=True, help_text="Optional name of the contributor's organisation, if applicable", max_length=100, null=True, verbose_name='Organisation')),
                ('description', models.TextField(blank=True, help_text='Optional details about the contributor or their organisation', null=True, verbose_name='Description')),
                ('contact', models.TextField(blank=True, help_text='Optional contact details of the contributor or organisation ', null=True, verbose_name='Contact details')),
                ('url', models.URLField(blank=True, help_text='Optional link to more details about the contributor or organisation', null=True, verbose_name='Link')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='glossary.glossaryindexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
