# Generated by Django 4.1.7 on 2023-02-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('webicons', '0003_alter_webicon_id'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartnersIndexPage',
            new_name='PartnersPage',
        ),
    ]
