# Generated by Django 4.1.9 on 2023-05-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webicons', '0001_initial'),
        ('about', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerspage',
            name='introduction_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webicons.webicon', verbose_name='Partners SVG Illustration'),
        ),
        migrations.AddField(
            model_name='partnerspage',
            name='partners_cta_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Partners call to action page'),
        ),
        migrations.AddField(
            model_name='partnerspage',
            name='partners_cta_image',
            field=models.ForeignKey(blank=True, help_text='A high quality image related to the Partners call to action message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Partners call to action Image'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bottom_call_to_action_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Bottom call to action button link'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='introduction_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Introduction Button Link'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='introduction_image',
            field=models.ForeignKey(blank=True, help_text='A high quality image related to your organisation as an organisation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Introduction Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='org_struct_img',
            field=models.ForeignKey(blank=True, help_text="A high quality image related to your organisation's structure", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Organisational Structure Image'),
        ),
    ]
