# Generated by Django 4.1.7 on 2023-03-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='mission',
            field=models.CharField(help_text="Organisation's mission", max_length=500, null=True, verbose_name="Organisation's mission"),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision',
            field=models.CharField(help_text="Organisation's vision", max_length=500, null=True, verbose_name="Organisation's vision"),
        ),
    ]
