# Generated by Django 4.1.7 on 2023-03-23 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('about', '0004_aboutpage_mission_aboutpage_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='org_struct_description',
            field=models.CharField(default='Our Organisational Structure', help_text="Organisation's Structure Description", max_length=500, null=True, verbose_name="Organisation's Struture Description"),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='org_struct_heading',
            field=models.CharField(default='Our Organisational Structure', help_text="Organisation's Structure Section Heading", max_length=250, null=True, verbose_name="Organisation's Struture Heading"),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='org_struct_img',
            field=models.ForeignKey(blank=True, help_text="A high quality image related to your organisation's structure", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Organisational Structure Image'),
        ),
    ]
