# Generated by Django 4.1.7 on 2023-03-23 13:40

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_aboutpage_org_struct_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='org_struct_description',
            field=wagtail.fields.RichTextField(default='Our Organisational Structure', help_text="Organisation's Structure Description", null=True, verbose_name="Organisation's Struture Description"),
        ),
    ]
