# Generated by Django 4.1.7 on 2023-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_aboutpage_org_struct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='bottom_call_to_action_heading',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bottom Call to action heading'),
        ),
    ]
