# Generated by Django 4.1.7 on 2023-05-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_aboutpage_additional_materials_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutindexpage',
            options={'verbose_name': 'About Index Page'},
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('order',), 'verbose_name': 'Partner'},
        ),
        migrations.AlterModelOptions(
            name='partnerspage',
            options={'verbose_name': 'Partners Page'},
        ),
    ]
