# Generated by Django 4.2.3 on 2024-04-23 14:52

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex_page', '0003_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('title_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100, verbose_name='Section Title')), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'code', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'hr', 'anchor', 'table', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull', 'indent', 'outdent', 'html'], help_text='Section description', verbose_name='Section Text'))])), ('title_text_image', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100, verbose_name='Section Title')), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'code', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'hr', 'anchor', 'table', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull', 'indent', 'outdent', 'html'], help_text='Section description', verbose_name='Section Text')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('accordion', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('collapsibles', wagtail.blocks.StreamBlock([('collapsibles', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4'])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))]))])), ('table', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'colHeaders': False, 'rowHeaders': False}))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
