# Generated by Django 4.1.7 on 2023-03-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webicons', '0003_alter_webicon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webicon',
            name='file',
            field=models.FileField(upload_to='svg'),
        ),
    ]
