# Generated by Django 4.2.18 on 2025-03-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_imagery', '0003_alter_satelliteimagerysetting_msg_layers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satelliteimagerypage',
            options={'verbose_name': 'Satellite Imagery Page'},
        ),
    ]
