# Generated by Django 4.1.5 on 2023-02-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialandaddresssettings',
            name='facebook',
            field=models.CharField(blank=True, help_text='Facebook handle', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='socialandaddresssettings',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram handle', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='socialandaddresssettings',
            name='youtube',
            field=models.CharField(blank=True, help_text='Youtube handle', max_length=250, null=True),
        ),
    ]
