# Generated by Django 4.1.7 on 2023-03-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementsettings',
            name='temp_units',
            field=models.CharField(choices=[('celsius', '°C'), ('fareinheit', '°F'), ('kelvin', 'K')], default='celsius', max_length=255),
        ),
        migrations.AlterField(
            model_name='measurementsettings',
            name='wind_units',
            field=models.CharField(choices=[('knots', 'knots'), ('km_p_hr', 'km/h'), ('mtr_p_s', 'm/s'), ('mile_p_hr', 'mph'), ('feet_p_s', 'ft/s')], default='km_p_hr', max_length=255),
        ),
    ]
