# Generated by Django 4.1.9 on 2023-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_integrationsettings_auto_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='auto_forecast',
            field=models.BooleanField(default=True, verbose_name='Enable automated forecasts'),
        ),
    ]
