# Generated by Django 4.1.7 on 2023-03-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_measurementsettings_temp_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='recaptcha_private_key',
            field=models.CharField(blank=True, help_text='Your Recaptcha Private Key', max_length=255, verbose_name='Recaptcha Private Key'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='recaptcha_public_key',
            field=models.CharField(blank=True, help_text='Your Recaptcha Public Key', max_length=255, verbose_name='Recaptcha Public Key'),
        ),
    ]
