# Generated by Django 4.1.7 on 2023-04-07 14:15

import django.core.validators
from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_integrationsettings_recaptcha_private_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Enable if this is the default theme', verbose_name='Is Default Theme')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Theme Name')),
                ('primary_color', wagtail_color_panel.fields.ColorField(blank=True, default='#363636', help_text='Primary color (use color picker)', max_length=7, null=True)),
                ('secondary_color', wagtail_color_panel.fields.ColorField(blank=True, default='#fff', help_text='Secondary color (use color picker)', max_length=7, null=True)),
                ('border_radius', models.IntegerField(default=4, help_text='Minimum 0 and Maximum 20 pixels', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Border radius (px)')),
                ('bs_hr_off', models.IntegerField(default=0, help_text='Minimum -100 and Maximum 100 pixels', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Horizontal Offset (px)')),
                ('bs_vt_off', models.IntegerField(default=1, help_text='Minimum -100 and Maximum 100 pixels', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Vertical Offset (px)')),
                ('bs_blur_rad', models.IntegerField(default=1, help_text='Minimum -100 and Maximum 100 pixels', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Blur radius (px)')),
                ('bs_spread_rad', models.IntegerField(default=-1, help_text='Minimum -100 and Maximum 100 pixels', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Spread radius (px)')),
                ('bs_color', wagtail_color_panel.fields.ColorField(blank=True, default='#363636', help_text='Box shadow color (use color picker)', max_length=7, null=True)),
                ('bs_color_opacity', models.DecimalField(decimal_places=3, default=0.125, help_text='Minimum 0 and Maximum 1', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Color opacity')),
            ],
        ),
    ]
