# Generated by Django 4.1.9 on 2023-06-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('site_settings', '0003_alter_organisationsetting_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationsettings',
            name='mailchimp_api',
        ),
        migrations.RemoveField(
            model_name='integrationsettings',
            name='zoom_api_key',
        ),
        migrations.RemoveField(
            model_name='integrationsettings',
            name='zoom_api_secret',
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='cms_logo',
            field=models.ForeignKey(blank=True, help_text='Logo that appears on the CMS. Should be a whit transparent logo preferably', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='CMS Logo'),
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Does not need to be any larger than 200x200 pixels. A 1:1 (square) image ratio is best here - If the image is not square, it will be scaled to a square.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='footer_logo',
            field=models.ForeignKey(blank=True, help_text='Logo that appears on the footer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Footer Logo'),
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='page_not_found_error_image',
            field=models.ForeignKey(blank=True, help_text='Image shown on error 404 page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Page not Found Image'),
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='server_error_image',
            field=models.ForeignKey(blank=True, help_text='Image shown on error 500 error page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Server Error Image'),
        ),
    ]
