# Generated by Django 4.1.5 on 2023-02-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_socialandaddresssettings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialandaddresssettings',
            name='phone',
            field=models.IntegerField(blank=True, help_text='Phone Number', null=True),
        ),
    ]
