# Generated by Django 4.1.7 on 2023-04-07 14:43

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='secondary_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#ffffff', help_text='Secondary color (use color picker)', max_length=7, null=True),
        ),
    ]
