# Generated by Django 4.1.5 on 2023-02-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('site_settings', '0004_alter_socialandaddresssettings_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_units', models.CharField(choices=[('celsius', '°C'), ('fareinheit', '°F')], default='celsius', max_length=255)),
                ('wind_units', models.CharField(choices=[('knots', 'knots'), ('km_p_hr', 'km/h'), ('m_p_s', 'm/s')], default='km_p_hr', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
