# Generated by Django 4.1.7 on 2023-04-10 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_alter_theme_secondary_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='bs_blur_rad',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='bs_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='bs_color_opacity',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='bs_hr_off',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='bs_spread_rad',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='bs_vt_off',
        ),
        migrations.AddField(
            model_name='theme',
            name='box_shadow',
            field=models.IntegerField(default=3, help_text='Elevation value minimum 1 and maximum 24', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Box shadow'),
        ),
    ]
