# Generated by Django 4.1.5 on 2023-02-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_measurementsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialandaddresssettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook handle', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='socialandaddresssettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram handle', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='socialandaddresssettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter handle', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='socialandaddresssettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='Youtube handle', max_length=250, null=True),
        ),
    ]
