# Generated by Django 4.1.7 on 2023-02-26 14:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_alter_socialandaddresssettings_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='The paired values of points defining a polygon that delineates the affected area of the alert message', null=True, srid=4326)),
            ],
        ),
    ]
