# Generated by Django 4.1.7 on 2023-04-10 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_alter_theme_box_shadow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='border_radius',
            field=models.IntegerField(default=6, help_text='Minimum 0 and Maximum 20 pixels', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Border radius (px)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='box_shadow',
            field=models.IntegerField(default=6, help_text='Elevation value minimum 1 and maximum 24', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Box shadow'),
        ),
    ]
