# Generated by Django 4.1.7 on 2023-04-10 12:28

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_theme_primary_hover_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='primary_hover_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#176c9c', help_text='Primary Hover color (use color picker)', max_length=7, null=True),
        ),
    ]
