# Generated by Django 4.1.7 on 2023-02-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_alter_countrysetting_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrysetting',
            name='country_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings.country'),
        ),
    ]
