# Generated by Django 4.1.7 on 2023-04-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_alter_theme_primary_hover_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementSettings',
        ),
    ]
