# Generated by Django 4.1.7 on 2023-02-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_alter_countrysetting_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrysetting',
            old_name='country_name',
            new_name='country',
        ),
    ]
