# Generated by Django 4.1.7 on 2023-05-02 14:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('site_settings', '0012_measurementsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationsettings',
            options={'verbose_name': 'Integration Settings'},
        ),
        migrations.AlterModelOptions(
            name='measurementsettings',
            options={'verbose_name': 'Measurement Settings'},
        ),
        migrations.AlterModelOptions(
            name='organisationsetting',
            options={'verbose_name': 'Organisation Settings'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Theme'},
        ),
        migrations.AlterField(
            model_name='country',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(help_text='The paired values of points defining a polygon that delineates the affected area of the alert message', null=True, srid=4326, verbose_name='Geometry'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(max_length=100, verbose_name='ISO'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='size',
            field=models.CharField(max_length=100, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='languagesettings',
            name='languages',
            field=wagtail.fields.StreamField([('languages', wagtail.blocks.StructBlock([('prefix', wagtail.blocks.CharBlock(max_length=5)), ('language', wagtail.blocks.CharBlock(max_length=20)), ('default', wagtail.blocks.BooleanBlock(required=False))]))], blank=True, null=True, use_json_field=False, verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='measurementsettings',
            name='temp_units',
            field=models.CharField(choices=[('celsius', '°C'), ('fareinheit', '°F'), ('kelvin', 'K')], default='celsius', max_length=255, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='measurementsettings',
            name='wind_units',
            field=models.CharField(choices=[('knots', 'knots'), ('km_p_hr', 'km/h'), ('mtr_p_s', 'm/s'), ('mile_p_hr', 'mph'), ('feet_p_s', 'ft/s')], default='km_p_hr', max_length=255, verbose_name='Wind'),
        ),
        migrations.AlterField(
            model_name='organisationsetting',
            name='address',
            field=wagtail.fields.RichTextField(blank=True, help_text='Postal Address', max_length=250, null=True, verbose_name='Postal address'),
        ),
        migrations.AlterField(
            model_name='organisationsetting',
            name='country',
            field=models.ForeignKey(default='Ethiopia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_setting', to='site_settings.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='organisationsetting',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='organisationsetting',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook url', max_length=250, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='organisationsetting',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram url', max_length=250, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='organisationsetting',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='organisationsetting',
            name='phone',
            field=models.IntegerField(blank=True, help_text='Phone Number', null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='organisationsetting',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter url', max_length=250, null=True, verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='organisationsetting',
            name='youtube',
            field=models.URLField(blank=True, help_text='Youtube url', max_length=250, null=True, verbose_name='Youtube URL'),
        ),
    ]
