# Generated by Django 4.0.10 on 2023-02-27 14:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('site_settings', '0013_alter_countrysetting_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', wagtail.fields.StreamField([('languages', wagtail.blocks.StructBlock([('prefix', wagtail.blocks.CharBlock(max_length=5)), ('language', wagtail.blocks.CharBlock(max_length=20)), ('default', wagtail.blocks.BooleanBlock(required=False))]))], blank=True, null=True, use_json_field=None)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Languages',
            },
        ),
    ]
