# Generated by Django 4.0.10 on 2023-02-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('site_settings', '0015_alter_languagesettings_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticssettings',
            name='ga_track_button_clicks',
            field=models.BooleanField(default=False, help_text='Track all button clicks using Google Analytics event tracking, Event tracking details can be specified in each button’s advanced settings options.', verbose_name='Track button clicks'),
        ),
        migrations.AlterField(
            model_name='analyticssettings',
            name='track_internally',
            field=models.BooleanField(default=False, help_text='Track   all pages internally. This will enable the internal analytics dashboard, alongside Google Analytics, if also enabled', verbose_name='Track pages internally'),
        ),
        migrations.CreateModel(
            name='OtherSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wagtail_form_key', models.CharField(blank=True, help_text='A Unique key for managing submitted forms")', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
