# Generated by Django 4.1.7 on 2023-02-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0016_alter_analyticssettings_ga_track_button_clicks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othersettings',
            name='wagtail_form_key',
            field=models.CharField(blank=True, help_text='A Unique key for managing submitted forms', max_length=255),
        ),
    ]
