# Generated by Django 4.2.2 on 2023-06-14 19:24

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('iso', models.CharField(max_length=100, verbose_name='ISO')),
                ('size', models.CharField(max_length=100, verbose_name='Size')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='The paired values of points defining a polygon that delineates the affected area of the alert message', null=True, srid=4326, verbose_name='Geometry')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDocumentModel',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtaildocs.document')),
                ('download_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'abstract': False,
            },
            bases=('wagtaildocs.document',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='base.product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Enable if this is the default theme', verbose_name='Is Default Theme')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Theme Name')),
                ('primary_color', wagtail_color_panel.fields.ColorField(blank=True, default='#363636', help_text='Primary color (use color picker)', max_length=7, null=True)),
                ('primary_hover_color', wagtail_color_panel.fields.ColorField(blank=True, default='#176c9c', help_text='Primary Hover color (use color picker)', max_length=7, null=True)),
                ('secondary_color', wagtail_color_panel.fields.ColorField(blank=True, default='#ffffff', help_text='Secondary color (use color picker)', max_length=7, null=True)),
                ('border_radius', models.IntegerField(default=6, help_text='Minimum 0 and Maximum 20 pixels', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Border radius (px)')),
                ('box_shadow', models.IntegerField(default=6, help_text='Elevation value minimum 1 and maximum 24', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Box shadow')),
            ],
            options={
                'verbose_name': 'Theme',
            },
        ),
        migrations.CreateModel(
            name='ProductItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_item_types', to='base.productcategory', verbose_name='Name')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wagtail_form_key', models.CharField(blank=True, help_text='A Unique key for managing submitted forms', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True, help_text='Twitter url', max_length=250, null=True, verbose_name='Twitter URL')),
                ('facebook', models.URLField(blank=True, help_text='Facebook url', max_length=250, null=True, verbose_name='Facebook URL')),
                ('youtube', models.URLField(blank=True, help_text='Youtube url', max_length=250, null=True, verbose_name='Youtube URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram url', max_length=250, null=True, verbose_name='Instagram URL')),
                ('phone', models.IntegerField(blank=True, help_text='Phone Number', null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True, verbose_name='Email address')),
                ('address', wagtail.fields.RichTextField(blank=True, help_text='Postal Address', max_length=250, null=True, verbose_name='Postal address')),
                ('cms_logo', models.ForeignKey(blank=True, help_text='Logo that appears on the CMS. Should be a whit transparent logo preferably', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='CMS Logo')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_setting', to='base.country', verbose_name='Country')),
                ('favicon', models.ForeignKey(blank=True, help_text='Does not need to be any larger than 200x200 pixels. A 1:1 (square) image ratio is best here - If the image is not square, it will be scaled to a square.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('footer_logo', models.ForeignKey(blank=True, help_text='Logo that appears on the footer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Footer Logo')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
                ('page_not_found_error_image', models.ForeignKey(blank=True, help_text='Image shown on error 404 page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Page not Found Image')),
                ('server_error_image', models.ForeignKey(blank=True, help_text='Image shown on error 500 error page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Server Error Image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Organisation Settings',
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_menu', wagtail.fields.StreamField([('navigation_item', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=False)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False)), ('include_subpages', wagtail.blocks.BooleanBlock(label='Include Subpages', required=False)), ('large_submenu', wagtail.blocks.BooleanBlock(label='Large Submenu Dropdown', required=False)), ('sub_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=False)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False))])))]))], blank=True, null=True, use_json_field=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasurementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_units', models.CharField(choices=[('celsius', '°C'), ('fareinheit', '°F'), ('kelvin', 'K')], default='celsius', max_length=255, verbose_name='Temperature')),
                ('wind_units', models.CharField(choices=[('knots', 'knots'), ('km_p_hr', 'km/h'), ('mtr_p_s', 'm/s'), ('mile_p_hr', 'mph'), ('feet_p_s', 'ft/s')], default='km_p_hr', max_length=255, verbose_name='Wind')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Measurement Settings',
            },
        ),
        migrations.CreateModel(
            name='LanguageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', wagtail.fields.StreamField([('languages', wagtail.blocks.StructBlock([('prefix', wagtail.blocks.CharBlock(max_length=5)), ('language', wagtail.blocks.CharBlock(max_length=20)), ('default', wagtail.blocks.BooleanBlock(required=False))]))], blank=True, null=True, use_json_field=True, verbose_name='languages')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_api', models.CharField(blank=True, help_text='To set up Youtube API Key refer to https://developers.google.com/youtube/v3/getting-started', max_length=50, verbose_name='Youtube API Key')),
                ('ga_tracking_id', models.CharField(blank=True, help_text='Your Google Analytics tracking ID (begins with "UA-")', max_length=255, verbose_name='GA Tracking ID')),
                ('ga_track_button_clicks', models.BooleanField(default=False, help_text='Track all button clicks using Google Analytics event tracking, Event tracking details can be specified in each button’s advanced settings options.', verbose_name='Track button clicks')),
                ('track_internally', models.BooleanField(default=False, help_text='Track   all pages internally. This will enable the internal analytics dashboard, alongside Google Analytics, if also enabled', verbose_name='Track pages internally')),
                ('recaptcha_public_key', models.CharField(blank=True, help_text='Your Recaptcha Public Key', max_length=255, verbose_name='Recaptcha Public Key')),
                ('recaptcha_private_key', models.CharField(blank=True, help_text='Your Recaptcha Private Key', max_length=255, verbose_name='Recaptcha Private Key')),
                ('enable_auto_forecast', models.BooleanField(default=True, verbose_name='Enable automated forecasts')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Integration Settings',
            },
        ),
        migrations.CreateModel(
            name='ImportantPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_alerts_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All alerts page')),
                ('all_applications_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All applications page')),
                ('all_events_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All events page')),
                ('all_news_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All news page')),
                ('all_partners_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All partners page')),
                ('all_products_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All products page')),
                ('all_projects_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All projects page')),
                ('all_publications_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All publications page')),
                ('all_tenders_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All tenders page')),
                ('all_vacancies_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All vacancies page')),
                ('all_videos_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All videos page')),
                ('contact_us_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Contact us page')),
                ('feedback_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='All feedback page')),
                ('mailing_list_signup_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Mailing list sign up page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('url', models.URLField(verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'GIS Application',
                'verbose_name_plural': 'GIS Applications',
            },
        ),
    ]
