# Generated by Django 4.2.2 on 2023-06-16 09:09

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_languagesettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationsetting',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='organisationsetting',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='organisationsetting',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='organisationsetting',
            name='youtube',
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='social_media_accounts',
            field=wagtail.fields.StreamField([('social_media_account', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=60)), ('fa_icon', wagtail.blocks.CharBlock(help_text="Font Awesome icon without the leading fab. E.g for Facebook, fa-facebook-f. Check the correct icon at <a target='_blank' href='https://fontawesome.com/icons?s=brands&m=free'>Font Awesome</a>. Type in on the search bar on that page to filter.", max_length=60, verbose_name='Font Awesome icon')), ('full_url', wagtail.blocks.URLBlock(help_text='The full url link that takes you to the page', max_length=255)), ('user_id', wagtail.blocks.CharBlock(help_text='The user id if available, For example the user Id/name for twitter, Instagram or channel id for Youtube etc', max_length=100, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
