# Generated by Django 4.2.2 on 2023-06-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_organisationsetting_social_media_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationsetting',
            name='country',
            field=models.CharField(blank=True, choices=[(None, 'Algeria'), (None, 'Angola'), (None, 'Benin'), (None, 'Botswana'), (None, 'Burkina Faso'), (None, 'Burundi'), (None, 'Cameroon'), (None, 'Cape Verde'), (None, 'Central African Republic'), (None, 'Chad'), (None, 'Comoros'), (None, 'Republic of Congo'), (None, "Côte d'Ivoire"), (None, 'Democratic Republic of the Congo'), (None, 'Djibouti'), (None, 'Egypt'), (None, 'Equatorial Guinea'), (None, 'Eritrea'), (None, 'Ethiopia'), (None, 'Gabon'), (None, 'Gambia'), (None, 'Ghana'), (None, 'Guinea'), (None, 'Guinea-Bissau'), (None, 'Kenya'), (None, 'Lesotho'), (None, 'Liberia'), (None, 'Libya'), (None, 'Madagascar'), (None, 'Malawi'), (None, 'Mali'), (None, 'Mauritania'), (None, 'Mauritius'), (None, 'Mayotte'), (None, 'Morocco'), (None, 'Mozambique'), (None, 'Namibia'), (None, 'Niger'), (None, 'Nigeria'), (None, 'Reunion'), (None, 'Rwanda'), (None, 'São Tomé and Príncipe'), (None, 'Senegal'), (None, 'Seychelles'), (None, 'Sierra Leone'), (None, 'Somalia'), (None, 'South Africa'), (None, 'South Sudan'), (None, 'Sudan'), (None, 'Swaziland'), (None, 'Tanzania'), (None, 'Togo'), (None, 'Tunisia'), (None, 'Uganda'), (None, 'Western Sahara'), (None, 'Zambia'), (None, 'Zimbabwe')], max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
