# Generated by Django 4.2.2 on 2023-06-16 13:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='footer_menu',
            field=wagtail.fields.StreamField([('navigation_item', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=False)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False)), ('include_subpages', wagtail.blocks.BooleanBlock(label='Include Subpages', required=False)), ('large_submenu', wagtail.blocks.BooleanBlock(label='Large Submenu Dropdown', required=False)), ('sub_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=False)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False))]))), ('is_action', wagtail.blocks.BooleanBlock(label='Show as action button', required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
