# Generated by Django 4.2.3 on 2023-08-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_productcategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionUpgradeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_version', models.CharField(max_length=100)),
                ('new_version', models.CharField(max_length=100)),
                ('checkpoint', models.CharField(choices=[('build', 'Build'), ('env_update', 'Env File Update'), ('recreate', 'Containers recreate'), ('final', 'Restarted')], max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
