# Generated by Django 4.2.3 on 2024-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_importantpages_cap_feed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='google_site_verification_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Site Verification Key'),
        ),
    ]
