# Generated by Django 4.2.3 on 2024-05-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_integrationsettings_google_site_verification_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['order'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
