# Generated by Django 4.2.3 on 2023-10-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partnerspage_partners_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerspage',
            name='introduction_button_link_external',
            field=models.URLField(blank=True, help_text='External Link if applicable. Ignored if internal page above is chosen', null=True),
        ),
    ]
