# Generated by Django 4.1.7 on 2023-02-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TendersIndexPage',
            new_name='TendersPage',
        ),
    ]
