# Generated by Django 4.2.3 on 2024-04-23 14:50

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpage',
            name='introduction_heading',
            field=models.CharField(blank=True, default='Meet Our Staff', help_text='Introduction section heading', max_length=100, null=True, verbose_name='Introduction Heading'),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='introduction_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introduction section description', null=True, verbose_name='Introduction text'),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='introduction_title',
            field=models.CharField(blank=True, help_text='Introduction section title', max_length=100, null=True, verbose_name='Introduction Title'),
        ),
    ]
