# Generated by Django 4.2.3 on 2023-10-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventpage_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventindexpage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='eventindexpage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='eventindexpage',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='eventindexpage',
            name='call_to_action_button_text',
        ),
        migrations.RemoveField(
            model_name='eventindexpage',
            name='call_to_action_related_page',
        ),
    ]
