# Generated by Django 4.2.7 on 2024-05-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_eventindexpage_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='enable_mailchimp_integration',
            field=models.BooleanField(default=False, verbose_name='Enable Mailchimp Integration in registration form'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='enable_zoom_integration',
            field=models.BooleanField(default=False, verbose_name='Enable Zoom Integration in registration form'),
        ),
    ]
