# Generated by Django 5.2.12 on 2026-04-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventpage_enable_mailchimp_integration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistrationpage',
            name='email_field',
            field=models.CharField(blank=True, default='email_address', help_text='The field in the form that corresponds to the email to use. Should be snake_cased', max_length=100, verbose_name='Email Field'),
        ),
    ]
