# Generated by Django 4.1.8 on 2023-04-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsurveyform', '0005_alter_surveysettings_parent_page_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveysettings',
            name='parent_page_type',
        ),
    ]
