# Generated by Django 4.2.2 on 2023-06-16 12:49

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='mission',
            field=models.CharField(blank=True, help_text="Organisation's mission", max_length=500, null=True, verbose_name="Organisation's mission"),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='org_struct_description',
            field=wagtail.fields.RichTextField(blank=True, help_text="Organisation's Structure Description", null=True, verbose_name="Organisation's Struture Description"),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='org_struct_heading',
            field=models.CharField(blank=True, default='Our Organisational Structure', help_text="Organisation's Structure Section Heading", max_length=250, null=True, verbose_name="Organisation's Struture Heading"),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision',
            field=models.CharField(blank=True, help_text="Organisation's vision", max_length=500, null=True, verbose_name="Organisation's vision"),
        ),
    ]
