# Generated by Django 4.2.7 on 2024-07-18 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aviation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stationcategory",
            options={
                "verbose_name": "Station Category",
                "verbose_name_plural": "Station Categories",
            },
        ),
    ]
