# Generated by Django 4.2.7 on 2024-07-23 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aviation", "0004_message_msg_datetime_alter_message_msg_format_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="msg_type",
        ),
    ]
