# Generated by Django 4.2.7 on 2024-08-01 13:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("aviation", "0006_aviationpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.CharField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Airport Name",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Airport Location (Lat, Lng)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Airport",
                "verbose_name_plural": "Airports",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="stationcategory",
            options={
                "verbose_name": "Airport Category",
                "verbose_name_plural": "Airport Categories",
            },
        ),
        migrations.RemoveField(
            model_name="message",
            name="station",
        ),
        migrations.DeleteModel(
            name="Station",
        ),
        migrations.AddField(
            model_name="airport",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="aviation.stationcategory",
                verbose_name="Airport Category",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="airport",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aviation.airport",
                verbose_name="Airport",
            ),
        ),
    ]
