# Generated by Django 4.1.7 on 2023-02-28 13:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='goals_block',
            field=wagtail.fields.StreamField([('goal', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'ul', 'ol', 'link', 'superscript', 'subscript'])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True, use_json_field=True, verbose_name='Goals'),
        ),
    ]
