# Generated by Django 4.1.7 on 2023-03-01 00:06

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_partnersindexpage_partnerspage'),
        ('projects', '0003_alter_projectpage_feature_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='partners',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='projects', to='about.partner'),
        ),
    ]
