# Generated by Django 4.1.9 on 2023-06-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectindexpage_introduction_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name of the project', max_length=50, null=True, verbose_name='Project short name'),
        ),
    ]
