MAPBOX_GL_STYLE_SPEC = {
    "PAINT_DEFAULTS": {
        "fill_color": "#000000",
        "fill_opacity": 1,
        "fill_outline_color": "#000000",
        "fill_antialias": True,

        "line_color": "#000000",
        "line_dasharray": "",
        "line_gap_width": 0,
        "line_opacity": 1,
        "line_width": 1,
        "line_offset": 0,

        "icon_color": "#000000",
        "icon_halo_blur": 0,
        "icon_halo_color": "#000000",
        "icon_halo_width": 0,
        "icon_opacity": 1,

        "text_color": "#000000",
        "text_halo_color": 0,
        "text_halo_width": 0,
        "text_translate": "",
        "text_translate_anchor": "map",

        "circle_color": "#000000",
        "circle_opacity": 1,
        "circle_radius": 5,
        "circle_stroke_color": "#000000",
        "circle_stroke_width": 0,
    },
    "LAYOUT_DEFAULTS": {
        "line_cap": "butt",
        "line_join": "miter",
        "line_miter_limit": 2,
        "line_round_limit": 1.05,

        "icon_allow_overlap": False,
        "icon_anchor": "center",
        "icon_ignore_placement": False,
        "icon_keep_upright": False,
        "icon_offset": "",
        "icon_optional": False,
        "icon_padding": 2,
        "icon_pitch_alignment": "auto",
        "icon_rotate": 0,
        "icon_rotation_alignment": "auto",
        "icon_size": 1,
        "icon_text_fit": "none",

        "symbol_placement": "point",
        "text_allow_overlap": False,
        "text_anchor": "center",
        "text_size": 16,
        "text_transform": "none",
        "text_ignore_placement": False,
        "text_justify": "center",
        "text_keep_upright": False,
        "text_letter_spacing": 0,
        "text_line_height": 1.2,
        "text_max_angle": 45,
        "text_max_width": 10,
        "text_offset": "",
        "text_opacity": 1,
        "text_padding": 2,
        "text_pitch_alignment": "auto",
        "text_radial_offset": 0,
        "text_rotate": 0,
        "text_rotation_alignment": "auto",
        "text_variable_anchor": "",
    }
}
