# Generated by Django 4.1.7 on 2023-04-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('mailchimper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MauticMailingListSubscriptionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('mautic_form_id', models.CharField(help_text='Form ID to use. Make sure you have created the form with all the required fields on Mautic', max_length=256, verbose_name='Mautic Form ID')),
                ('thank_you_text', models.TextField(blank=True, help_text='Message to show on successful submission', null=True)),
                ('heading', models.CharField(blank=True, help_text='Heading', max_length=255, null=True)),
                ('introduction_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
