# Generated by Django 4.1.7 on 2023-05-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimper', '0003_rename_mailinglistsubscriptionpage_mailchimpmailinglistsubscriptionpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailchimpmailinglistsubscriptionpage',
            name='heading',
            field=models.CharField(blank=True, help_text='Heading', max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='mailchimpmailinglistsubscriptionpage',
            name='introduction_text',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction text'),
        ),
        migrations.AlterField(
            model_name='mailchimpmailinglistsubscriptionpage',
            name='thank_you_text',
            field=models.TextField(blank=True, help_text='Message to show on successful submission', null=True, verbose_name='Thank you text'),
        ),
        migrations.AlterField(
            model_name='mauticmailinglistsubscriptionpage',
            name='heading',
            field=models.CharField(blank=True, help_text='Heading', max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='mauticmailinglistsubscriptionpage',
            name='introduction_text',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction text'),
        ),
    ]
