# Generated by Django 4.1.7 on 2023-02-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='show_in_rcc',
        ),
    ]
