# Generated by Django 4.1.7 on 2023-03-01 22:06

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventpage_show_in_rcc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Africa/Nairobi', help_text='Timezone'),
        ),
    ]
