# Generated by Django 4.1.9 on 2023-05-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistrationpage',
            name='enable_mailing_list_subscription',
        ),
        migrations.RemoveField(
            model_name='eventregistrationpage',
            name='mailing_list_checkbox_label',
        ),
        migrations.RemoveField(
            model_name='eventregistrationpage',
            name='subscriber_json_data',
        ),
    ]
