# Generated by Django 4.1.9 on 2023-05-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventregistrationpage_enable_mailing_list_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistrationpage',
            name='audience_list_id',
            field=models.CharField(blank=True, help_text='Select MailChimp Audience to add users to', max_length=50, null=True, verbose_name='MailChimp Audience'),
        ),
        migrations.AddField(
            model_name='eventregistrationpage',
            name='interest_categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistrationpage',
            name='mailing_list_checkbox_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mailing list checkbox label'),
        ),
        migrations.AddField(
            model_name='eventregistrationpage',
            name='merge_fields_mapping',
            field=models.TextField(blank=True, null=True),
        ),
    ]
