# Generated by Django 4.1.7 on 2023-03-01 22:07

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventpage_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Africa/Nairobi', help_text='Timezone', use_pytz=False),
        ),
    ]
