# Generated by Django 4.1.9 on 2023-05-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventregistrationpage_audience_list_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='zoom_events_id',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='zoom_events_url',
        ),
        migrations.RemoveField(
            model_name='eventregistrationpage',
            name='enable_adding_registrants',
        ),
        migrations.RemoveField(
            model_name='eventregistrationpage',
            name='is_webinar',
        ),
        migrations.RemoveField(
            model_name='eventregistrationpage',
            name='zoom_json_data',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='zoom_event',
            field=models.TextField(blank=True, help_text='Select Zoom Event', null=True, verbose_name='Zoom Event'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='zoom_reg_fields_mapping',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistrationpage',
            name='zoom_event',
            field=models.TextField(blank=True, help_text='Select Zoom Event', null=True, verbose_name='Zoom Event'),
        ),
        migrations.AddField(
            model_name='eventregistrationpage',
            name='zoom_reg_fields_mapping',
            field=models.TextField(blank=True, null=True),
        ),
    ]
