# Generated by Django 4.1.9 on 2023-06-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventpage_zoom_events_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='zoom_event',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='zoom_reg_fields_mapping',
        ),
    ]
