# Generated by Django 4.1.7 on 2023-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventpage_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='feature_img_src',
            field=models.TextField(blank=True, null=True),
        ),
    ]
