# Generated by Django 4.1.9 on 2023-06-13 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventindexpage_search_image_eventpage_search_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventregistrationformtemplate', verbose_name='Form template'),
        ),
    ]
