# Generated by Django 4.1.9 on 2023-06-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productcategory_product'),
        ('events', '0008_alter_eventpage_form_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='agenda_document',
            field=models.ForeignKey(blank=True, help_text='Agenda document, if available, preferably in PDF format', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customdocumentmodel', verbose_name='Downloadable agenda document'),
        ),
    ]
