# Generated by Django 4.1.7 on 2023-05-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventindexpage_options_alter_eventpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistrationpage',
            name='enable_mailing_list_subscription',
            field=models.BooleanField(default=False, verbose_name='Enable Mailing list subscription'),
        ),
        migrations.AlterField(
            model_name='eventregistrationpage',
            name='mailing_list_checkbox_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mailing list checkbox label'),
        ),
    ]
