# Generated by Django 4.2.7 on 2024-07-18 19:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid
import wagtail_color_panel.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Category name")),
                (
                    "color",
                    wagtail_color_panel.fields.ColorField(
                        blank=True,
                        default="#363636",
                        help_text="Category color",
                        max_length=7,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique UUID. Auto generated on creation.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, null=True, unique=True, verbose_name="City Name"
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="City Location (Lat, Lng)"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aviation.stationcategory",
                        verbose_name="Station Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msg_encode",
                    models.TextField(verbose_name="Message in Encoded Form"),
                ),
                (
                    "msg_decode",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Decoded Message"
                    ),
                ),
                (
                    "msg_type",
                    models.CharField(
                        choices=[
                            ("observation", "Observation"),
                            ("forecast", "Forecast"),
                        ],
                        max_length=50,
                        verbose_name="Message Type",
                    ),
                ),
                (
                    "msg_format",
                    models.CharField(
                        choices=[("metar", "METAR"), ("taf", "TAF")],
                        max_length=50,
                        verbose_name="Message Format",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aviation.station",
                        verbose_name="Station",
                    ),
                ),
            ],
        ),
    ]
