# Generated by Django 4.2.7 on 2024-07-18 20:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aviation", "0002_alter_stationcategory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="station",
            options={
                "ordering": ["name"],
                "verbose_name": "Station",
                "verbose_name_plural": "Stations",
            },
        ),
        migrations.AlterField(
            model_name="station",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Station Location (Lat, Lng)"
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Station Name"
            ),
        ),
    ]
