# Generated by Django 4.2.7 on 2024-08-01 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aviation", "0007_airport_alter_stationcategory_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StationCategory",
            new_name="AirportCategory",
        ),
    ]
