# Generated by Django 4.1.8 on 2023-04-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsurveyform', '0002_surveyformpage_remove_formpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyformpage',
            name='name',
        ),
    ]
