# Generated by Django 4.1.9 on 2023-06-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productgroup_producttype'),
        ('products', '0002_alter_productitempage_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitempage',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customdocumentmodel', verbose_name='Document'),
        ),
    ]
