# Generated by Django 4.1.7 on 2023-02-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('core', '0005_remove_application_show_in_geoportal'),
        ('products', '0002_rename_productindexpage_productpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPage',
            new_name='ProductIndexPage',
        ),
    ]
