# Generated by Django 4.1.9 on 2023-06-12 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_productitemtype_remove_producttype_group_and_more'),
        ('products', '0004_productitempage_search_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitempage',
            name='document',
        ),
        migrations.RemoveField(
            model_name='productitempage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productitempage',
            name='month',
        ),
        migrations.RemoveField(
            model_name='productitempage',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='productitempage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='productitempage',
            name='year',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='earliest_bulletin_year',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='feature_block',
        ),
        migrations.AddField(
            model_name='productitempage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='productitempage',
            name='products',
            field=wagtail.fields.StreamField([('image_product', wagtail.blocks.StructBlock([('product_type', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description', wagtail.blocks.RichTextBlock())], label='Image')), ('document_product', wagtail.blocks.StructBlock([('product_type', wagtail.blocks.CharBlock(required=True)), ('thumbnail', wagtail.images.blocks.ImageChooserBlock(required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('description', wagtail.blocks.RichTextBlock())], label='Document'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='productitempage',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Up to when is this product valid ? Leave blank if not applicable', null=True, verbose_name='Valid until'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Product'),
        ),
    ]
