# Generated by Django 4.1.7 on 2023-03-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('products', '0006_rename_productdetailpage_productitempage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsIndexPage',
            new_name='ProductIndexPage',
        ),
    ]
