# Generated by Django 4.1.9 on 2023-06-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productitempage_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='call_to_action_button_text',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='call_to_action_related_page',
        ),
    ]
