# Generated by Django 4.1.9 on 2023-06-13 09:24

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productpage_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitempage',
            name='products',
            field=wagtail.fields.StreamField([('image_product', wagtail.blocks.StructBlock([('product_type', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description', wagtail.blocks.RichTextBlock())], label='Image')), ('document_product', wagtail.blocks.StructBlock([('product_type', wagtail.blocks.CharBlock(required=True)), ('thumbnail', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('description', wagtail.blocks.RichTextBlock())], label='Document'))], default='', use_json_field=True),
            preserve_default=False,
        ),
    ]
