# Generated by Django 4.1.7 on 2023-04-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productpage_all_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='all_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productpage', verbose_name='Products'),
        ),
    ]
