# Generated by Django 4.1.7 on 2023-05-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productitempage_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner Subtitle'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='banner_title',
            field=models.CharField(max_length=255, verbose_name='Banner Title'),
        ),
    ]
