# Generated by Django 4.1.7 on 2023-05-02 07:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_theme'),
        ('products', '0015_alter_productitempage_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.productcategory', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicecategory', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='productpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='products.productitempage', verbose_name='Product Tag'),
        ),
    ]
