# Generated by Django 4.1.7 on 2023-05-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productpage_product_alter_productpage_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productindexpage',
            options={'verbose_name': 'Product Index Page', 'verbose_name_plural': 'Product Index Pages'},
        ),
        migrations.AlterModelOptions(
            name='productitempage',
            options={'verbose_name': 'Product Item'},
        ),
        migrations.AlterModelOptions(
            name='productpage',
            options={'verbose_name': 'Product Page', 'verbose_name_plural': 'Product Pages'},
        ),
    ]
